### ISSUE TITLE
Ask for 'startBlock' during 'graph init' and 'graph add'

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-tooling#1007]
One caveat that new subgraph developers always fall into is not specifying a startBlock. That makes the subgraph super slow to start indexing useful data. We should ask for startBlock during the init and add dialogs. Best would be to get it automatically like described here: #917. But this issue describes a quicker way to implement and a fallback if an external source is not available.

**Comment by bmarcot** [comment]
It would be a great addition to the `graph add` command, that will permit to use the command from scripts without having to manually edit afterward.

**Comment by schmidsi** [comment]
@bmarcot like a command line argument: `graph add 0xdeadbeef.... --start-block 123`?

**Comment by bmarcot** [comment]
@schmidsi yes!

**Comment by schmidsi** [comment]
@dotansimha, @incrypto32 is already working on this feature since it is a good first issue to learn the codebase. Just to let you know 😊
