### ISSUE TITLE
Graph CLI 0.37.1 Doesn't Complete Setup 

### ISSUE THREAD

**Issue by marcusrein** [graphprotocol/graph-tooling#1045]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

I just set up a new Macbook Pro and installed a fresh copy of node, nvm, VScode, and graph-cli (globally). I was spinning up a subgraph for a contract on Goerli and was getting the error seen in the attached photo after setting the path to my ABI.

I checked package.json and saw this:

```
  "dependencies": {
    "@graphprotocol/graph-cli": "undefined",
    "@graphprotocol/graph-ts": "0.29.1"
  },
```
I reported this to TheGraph's discord at this point. 

I changed the "undefined" line to:

`    "@graphprotocol/graph-cli": "0.37.1",
`
 Then ran npm install, and it completed.

This was helpful to keep going, but every time I ran the CLI, the same bug would occur. 

I downgraded the CLI 0.37.0 and the CLI error did not occur.

<img width="653" alt="Screenshot 2023-01-19 at 5 22 46 PM" src="https://user-images.githubusercontent.com/64141593/213578336-860798d5-dbaf-428d-b25d-17e7814fee9d.png">

### Reproduction

www.thegraph.com

### Steps to Reproduce the Bug or Issue

1. Install GraphCLI globally npm install -g @graphprotocol/graph-cli
2. Run the CLI graph init --studio <subgraph-name>
3. Continue filling out CLI prompts, CLI glitches out after entring path to ABI.

See previously attached photo for bug. 

### Expected behavior

CLI continues as it usually does in 0.37.0.

### Screenshots or Videos

<img width="653" alt="Screenshot 2023-01-19 at 5 22 46 PM" src="https://user-images.githubusercontent.com/64141593/213579903-5cb0a772-b88e-41e6-bf8f-b26c08e6543f.png">

### Platform

- OS: [e.g. macOS]
- NodeJS: [e.g. 19.4.0]
- `@graphprotocol/*` version(s): 0.37.1. 

### Subgraph Manifest

Error was prior to subgraph.yaml being created

### Subgraph GraphQL Schema

Error was prior to this schema.graphql being created

### Additional context

Thanks! Let me know if theres any other info needed!

**Comment by dotansimha** [comment]
@marcusrein can you please try latest? `0.37.6`
this was fixed before by @enisdenjo

**Comment by marcusrein** [comment]
updated - works like a charm, thanks!
