### ISSUE TITLE
graph init command failed

### ISSUE THREAD

**Issue by VaibhavArora19** [graphprotocol/graph-tooling#1052]
While initializing graph using command `garph init`, installing dependencies with yarn fails because `request` is no longer being maintained as stated by `request` team here https://github.com/request/request/issues/3142/#issue-427331880 with the following error.
![Screenshot (26)](https://user-images.githubusercontent.com/82141868/215492896-051b0ba3-2bed-4950-8238-50bb091f3ef7.png)

**Comment by saihaj** [comment]
@VaibhavArora19 so I tried `graph init` on new project. I do not get the error you see. (But found a new error on lists while debugging this https://github.com/graphprotocol/graph-tooling/issues/1058)

[![asciicast](https://asciinema.org/a/HvEb9ZoUhbwtGVUB3KrKRYWLs.svg)](https://asciinema.org/a/HvEb9ZoUhbwtGVUB3KrKRYWLs)

**Comment by VaibhavArora19** [comment]
Not sure if this is a windows specific problem but I tried changing my node version to `16.17.0` as well, `graph-cli v0.38.0` and I am still having the same error as I was having before. I've seen some other devs as well facing the same issue. Some screenshots attached below of the same problem that other people faced.

 
![Screenshot (36)](https://user-images.githubusercontent.com/82141868/216587880-ccd304dd-75a9-4f1e-a1bf-7ba7f57450ff.png)
![Screenshot (37)](https://user-images.githubusercontent.com/82141868/216587892-09d60944-0931-4be1-bb37-dbf2d27f0878.png)

**Comment by PerminovEugene** [comment]
I had an error when I tried to launch graph init in my project folder, where package.json and yarn.lock files existed. However, when I ran the same command outside of the project folder, it worked fine. I think this might be a workaround for people who are experiencing this problem.
