### ISSUE TITLE
Name collision with event property `set` in generated code

### ISSUE THREAD

**Issue by reilgun** [graphprotocol/graph-tooling#1056]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli, @graphprotocol/graph-ts

### Describe the issue

I started a subgraph project using the cli for an EVM (BSC) smart contract, added the contract address during the interactive process, and had the cli fetch the ABI and generate everything.

When doing `graph build` it fails, with a number of errors like this:

```
ERROR TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'i32' has no compatible call signatures.

     this.set("set", Value.fromI32(value));
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in generated/schema.ts(394,5)

ERROR TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'i32' has no compatible call signatures.

     this.set("blockNumber", Value.fromBigInt(value));
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 in generated/schema.ts(403,5)

ERROR TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'i32' has no compatible call signatures.

     this.set("blockTimestamp", Value.fromBigInt(value));
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The problem is that one of my events logs a property called `set`, type `i32`, which evidently conflicts with `Entity.set()`

### Reproduction

graph cli

### Steps to Reproduce the Bug or Issue

1. Create new EVM subgraph using the cli
2. Add a contract with an event that contains a property called `set`
3. `graph codegen` (succeeds)
4. `graph build` (fails)

### Expected behavior

I believe this sort of name collision should be detected and the event property auto-renamed.
Or perhaps it should suggest that this might be the problem and how to work around this.

### Platform

- OS: Windows
- NodeJS: v16.14.0
- "@graphprotocol/graph-cli": "0.37.7",
- "@graphprotocol/graph-ts": "0.29.1"

**Comment by alex-pakalniskis** [comment]
can't reproduce
