### ISSUE TITLE
current latest release 0.40.0 cannot build substreams type subgraph.yaml

### ISSUE THREAD

**Issue by tw7613781** [graphprotocol/graph-tooling#1067]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

I was trying to build and deploy the following subgraph.yaml to a graph node, which connects firehose endpoints. but it fails when run the cmd "graph build --ipfs http://localhost:5001 subgraph.yaml", an error "Globals file is missing." presents with graph-cli@0.40.0. After downgrade to graph-cli@0.37.1, it succeeds.

The error happens here: https://github.com/graphprotocol/graph-tooling/blob/71578d6aa5b5f2000e2eff2d5f358264de0332c2/packages/cli/src/compiler/index.ts#L77

The logic seems has be modified after the feature merge: https://github.com/graphprotocol/graph-tooling/pull/991

### Reproduction

https://github.com/streamingfast/substreams-eth-block-meta/tree/feature/graph-node

### Steps to Reproduce the Bug or Issue

1. run a graph node: go to graph-node subfolder, run "sudo docker compose up -d" with ENV variables set
2. compile substreams module and deploy the subgraph.yaml to graph node: go the top folder, run "make deploy_local: package"

if your graph-cli version is 0.40.0, the error "Globals file is missing." will presents

### Expected behavior

latest version should supports building substreams type subgraph.yaml

### Platform

- OS: ubuntu 20
- NodeJS: 16
- @graphprotocol/graph-cli: 0.40.0

**Comment by saihaj** [comment]
hey @tw7613781 I did a fix here https://github.com/graphprotocol/graph-tooling/pull/1071 can you try `@graphprotocol/graph-cli@0.41.0-alpha-20230217171853-0aeab7b`

**Comment by saihaj** [comment]
we released a new version let us know if this issue still persists https://github.com/graphprotocol/graph-tooling/releases/tag/release-1676926121312
