### ISSUE TITLE
whenever we update assemblyscript we should give user warning so they are aware

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1072]
It would be nice to give users warnings that a AssemblyScript version was upgraded. Since AssemblyScript currently does not have a stable version we should have better education

Context: https://github.com/graphprotocol/graph-tooling/issues/1022

**Comment by azf20** [comment]
hey - we did quite a lot of warning etc. and there are docs on the upgrade here, which happened some time ago now https://thegraph.com/docs/en/release-notes/assemblyscript-migration-guide/
I wonder if we might need to update again (should be less severe as last time it was from a very early version)

**Comment by azf20** [comment]
Closing this issue but we should do this when we update Assemblyscript https://github.com/graphprotocol/graph-tooling/issues/1187
