### ISSUE TITLE
create a new subgraph from CLI

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1082]
> We’re adding new subgraphs for OpenZeppelin Defender, but it’s been problematic that only new subgraphs can be added via UI and only by Github Org Admins, is there any suggestions from your side on how to approach a team-wide permission only for creating the subgraphs?
We can use the Access Token provided to deploy, but subgraph creation is also not allowed via API, and we might need to add new networks every once in a while (specially as you add support as well)

Although there is a `graph create` command in the CLI, it does not work on the hosted service or subgraph studio:

```bash
graph create [options] <subgraph-name>
Options:
-g, --node <url>              Graph node to create the subgraph in
➜  ~ graph create --access-token TOKEN --node https://api.thegraph.com/deploy/ schmidsi/tests-api
✖ Error creating the subgraph: Creating subgraphs only available from hosted-service dashboard. https://thegraph.com/hosted-service/dashboard
➜  ~ 
➜  ~ 
➜  ~ graph create --access-token TOKEN --node https://api.studio.thegraph.com/deploy/ qwerqewr
✖ Error creating the subgraph: Method not found
````

**Comment by incrypto32** [comment]
Directly creating the subgraph on the hosted service graph node just with the access token is not neccessary. Maybe we can just warn the user that the subgraph doesn't exist and if it doesn't maybe open the browser and redirect to the create subgraph page ?

**Comment by saihaj** [comment]
> Maybe we can just warn the user that the subgraph doesn't exist and if it doesn't maybe open the browser and redirect to the create subgraph page ?

yeah I think this is a good start to improve the UX here to start with
