### ISSUE TITLE
Using a `derivedFrom` field in the graph code gives no compile time issues but fails when the graph syncs

### ISSUE THREAD

**Issue by JasoonS** [graphprotocol/graph-tooling#1093]
Taking this example from your docs:

```graphql
type Token @entity {
  id: ID!
  tokenBalances: [TokenBalance!]! @derivedFrom(field: "token")
}

type TokenBalance @entity {
  id: ID!
  amount: Int!
  token: Token!
}
```

If in a handler you were to write:
```typescript
let someToken = Token.load("some-token-id");
let tokenBalances = someToken.tokenBalances;
```

You get no compile errors, but you get an error similar to the following when the graph node tries to sync:
```
ERRO Handler skipped due to execution failure, error: Mapping aborted at generated/schema.ts, line 736, column 12, with message: unexpected null	wasm backtrace:	    0: 0x91f2 - !src/mappings/longShort/handleSystemStateUpdated	, handler: handleSystemStateUpdated, block_hash: 0xf361376dc0a066341e0a89bbcaf867941a8f697d70a90627fc74fb7bda165038, block_number: 44, sgd: 5, subgraph_id: QmNPHGChErgtPD3oMru8Dpo96KWYUWgsQM8ye6sQvbtUsE, component: SubgraphInstanceManager
```

It would be very useful to be able to fetch the `derivedFrom` fields just as you can fetch normal fields. Otherwise using `derivedFrom` fields can be somewhat limiting. These should be read-only fields, but behave like normal fields in all other ways.

**Comment by azf20** [comment]
Fetching derived fields is being worked on here https://github.com/graphprotocol/graph-node/issues/4004

**Comment by obernardovieira** [comment]
> This is is tricky because of the entity cache but would be possible to support in graph node. However looping over a stored collection in a mapping is never good for indexing performance, so it's worth looking into the use cases and checking if they could not be better covered by other improvements such as indexing-time aggregations.

going through this, I'm thinking; it does make sense that it's explosive and it makes sense to not iterate over it. But given that, I have a question.

Lets suppose I have entities `Borrower` and `Loan`. `Borrower` id is user address and `Loan` id is user address and loan index (like below). Now suppose, the user wants to change the address. What now? What's the best way to update without this taking too much processing?

```graphql
type Borrower @entity {
  # borrower id
  id: ID!
  # borrower loans
  loans: [Loan!]! @derivedFrom(field: "borrower")
}

type Loan @entity {
  # loan id {{ userAdreress }}-{{ loanId }}
  id: ID!
  # loan index
  index: Int!
  # borrower address
  borrower: Borrower!
}
```

**Comment by azf20** [comment]
I think if the user address can change, you may not want to embed the user address in the loan ID, and if this is an expected and common action, you might want to use another means of specifying the borrower (e.g. borrowerId, which is an incrementing list, with a mapping to the current associated address).
