### ISSUE TITLE
[Feature Request] getCreate2Address & pack

### ISSUE THREAD

**Issue by matthewlilley** [graphprotocol/graph-tooling#1101]
It would be useful to be able to have available some common functions like getCreate2Address and pack to reduce calls where computation maybe a valid approach instead.

References:

https://github.com/ethers-io/ethers.js/blob/master/packages/address/src.ts/index.ts#L143
https://github.com/ethers-io/ethers.js/blob/master/packages/solidity/src.ts/index.ts#L84

**Comment by schmidsi** [comment]
@saihaj this is done, no?

**Comment by saihaj** [comment]
I didn't get to do pack but `create2` is available now!
