### ISSUE TITLE
How to recover one failed subgraph?

### ISSUE THREAD

**Issue by lansehuiyi6** [graphprotocol/graph-tooling#1102]
Hi, I want to know how to recover one failed healthy subgraph if subgraph sync failed because of rpc issue? 
For now, i just re-deploy one, and wait it sync to latest block. Any better idea? 

Connection checkout timed out, backtrace:    0: <graph_store_postgres::connection_pool::EventHandler as r2d2::event::HandleEvent>::handle_timeout
   1: r2d2::Pool<M>::get_timeout
   2: graph_store_postgres::connection_pool::PoolInner::get_with_timeout_warning
   3: graph_store_postgres::deployment_store::DeploymentStore::get_replica_conn
   4: <graph_store_postgres::query_store::QueryStore as graph::components::store::QueryStore>::find_query_values
   5: graph_graphql::store::prefetch::execute_field
   6: graph_graphql::store::prefetch::execute_selection_set
   7: graph_graphql::store::prefetch::run
   8: <graph_graphql::store::resolver::StoreResolver as graph_graphql::execution::resolver::Resolver>::prefetch
   9: graph_graphql::execution::execution::execute_root_selection_set_uncached
  10: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
  11: tokio::runtime::task::harness::Harness<T,S>::poll
  12: tokio::runtime::blocking::pool::Inner::run
  13: std::sys_common::backtrace::__rust_begin_short_backtrace
  14: core::ops::function::FnOnce::call_once{{vtable.shim}}
  15: std::sys::unix::thread::Thread::new::thread_start
  16: start_thread
  17: clone
, wait_ms: 5000, pool: main, shard: primary, component: ConnectionPool

 WARN Trying again after block polling failed: Transport error: Unexpected response status code: 429 Too Many Requests, provider: mainnet-rpc-0, component: BlockIngestor

**Comment by azf20** [comment]
Automatic retries are available for non-deterministic errors
