### ISSUE TITLE
code generation strongs

### ISSUE THREAD

**Issue by purplecity** [graphprotocol/graph-tooling#1106]
solidity code will emit uint256[] array event

```
 event AttrbuteUpdated(uint256 tokenID,uint256[]  indexed attrID,uint256[]  indexed value);
```

but use yarn codegen then will convert to Bytes.

```
  get attrID(): Bytes {
    return this._event.parameters[1].value.toBytes();
  }

  get value(): Bytes {
    return this._event.parameters[2].value.toBytes();
  }
```

i will record attrID/value at one enitity. how to do it...

```
type Token @entity {
  id: ID!
  contract: GameERC721Contract!
  owner: Owner!
  tokenID: BigInt!
  tokenURI: String!
  mintTime: BigInt!
  attrID:[BigInt!]!
  attrValue:[BigInt!]!
}
```

**Comment by azf20** [comment]
As the attrId and attrValue are `indexed`, they are stored as topics, which can only store a single word, so the `bytes` made available here is the keccak-256 hash of the value https://docs.soliditylang.org/en/develop/contracts.html#events
