### ISSUE TITLE
Manually check for null on all arguments

### ISSUE THREAD

**Issue by leoyvens** [graphprotocol/graph-tooling#1108]
In typescript a type such as `string` is non-nullable by default and it's nullable version is `string | null`. But strict null checking is not properly implemented in AssemblyScript [yet](https://github.com/AssemblyScript/assemblyscript/issues/233). The node currently assumes all pointers passed to it are non-null, and since this is consistent with regular ts semantics I'd rather catch nulls in the mappings than in the node, so we should just add null checks everywhere in this library.

**Comment by azf20** [comment]
Fixed in the upstream
