### ISSUE TITLE
Support NodeJS APIs via https://github.com/AssemblyScript/node

### ISSUE THREAD

**Issue by eccentricexit** [graphprotocol/graph-tooling#1113]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
To use packages like `ethereumjs/rlp`, we need to first port them to AssemblyScript. This has been proving cumbersome since we are missing some NodeJS APIs such as `Buffer`.

**What is the expected behavior?**
Ideally we should be able to just use `fs` or `Buffer` inside subgraph mappings. Perhaps adding https://github.com/AssemblyScript/node is a solution.

**Comment by azf20** [comment]
Closing this as with Assemblyscript support >0.19.x this should now be available, please re-open if not
