### ISSUE TITLE
Event params' type in invoked handlers are not the same as declared in event signature

### ISSUE THREAD

**Issue by atom-yang** [graphprotocol/graph-tooling#1114]
Related Contract: https://etherscan.io/address/0x3f966fa1c0606e19047ed72068d2857677e07ef4#code
Related Event: `event Harvested(address, address, uint256)`
Related Code: 
```typescript
export function handleNewHarvest(event: NewHarvestedEvent): void {
  // output: handle new harvest 0 type 4
  log.debug('handle new harvest 0 type ' + event.parameters[0].value.kind.toString(), []);
  // output: handle new harvest 1 type 4
  log.debug('handle new harvest 1 type ' + event.parameters[1].value.kind.toString(), []);
  // output: handle new harvest 2 type 4
  log.debug('handle new harvest 2 type ' + event.parameters[2].value.kind.toString(), []);
  // throw an error
  let profitTokenAddress = changetype<Address>(event.parameters[1].value.data as u32);
 // throw an error, related to https://github.com/graphprotocol/graph-ts/blob/fdd8f835316c68c66eb9fd9917c2c5c8f07bf904/chain/ethereum.ts#L38, since param0's ValueKind is 4, which is uint
  event.params.param0;
}
```
## Problem
in the event `Harvested(address, address, uint256)`, the param0 and param1's type is `Address`, but in the process of scanning, when trigger the callback function `handleNewHarvest()`, the params' type become `uint`, not Address, so I can't use `event.params.param0`, since it calls the method `toAddress()`, which has an assert.

So I tried to copy the code you convert the original data, but it still failed, probably the original data has been cut since different type.

Wish to get your support, thanks.

**Comment by leoyvens** [comment]
We haven't gotten a new report of this in a long time, I think we can close.
