### ISSUE TITLE
Feature Request: Return entity data in the console to improve debugging experience

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-tooling#1119]
It is possible to get errors from either our graph-ts library or the ASC compiler, and it is really hard to tell what the error is, and it fails, and we don't indicate which value failed. 

For example, `graph-ts` might indicate that `Value is not a BigInt`, but it is hard to tell what line this came from, and what the value was. This often happens when it is null. Other issues are dealing with unexpected divide by 0, or misinterpreting the type from the beginning. 

Daostack kind of does this [here](https://github.com/daostack/subgraph/blob/5359d51db1f48cb39636b910b7e41c6774886414/src/utils.ts#L41), but we just want a method like `debug(msg: string)` instead of an entity type.

Ideally this is what it would do : 

- On fail, it tells you which line it failed on (we already know the handler it failed on
- It gives us the value that it failed with, and prints it to the console
- it still gives us the error message we get today

**Comment by azf20** [comment]
The line it failed on is now logged by Graph Node (the error message is printed, I don't think that always provides the value it failed with - there is also now much more substantial logging in Graph Node)
