### ISSUE TITLE
Ability to have background processes to deal with external data

### ISSUE THREAD

**Issue by wighawag** [graphprotocol/graph-tooling#1121]
While graph-ts allow you to use ipfs api, it is possible that the data is not available on ipfs at the time of the query.

Actually graph-ts allow you to do something about it since it would return null after a timeout.

Now it would be great that we could queue some background processes to run so they can fetch the ipfs data regularly until available.

This way the data encoded in the ipfs file can populate the db at a later time/

We still need to consider reorg but something like that should be possible.

I would extend that to any kind of background processes though.

**Comment by azf20** [comment]
this is now available via file data sources https://forum.thegraph.com/t/gip-file-data-sources/2721/6
