### ISSUE TITLE
Feature Request: Add in indexing with Typed maps

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-tooling#1123]
Right now, direct index lookups of a typed map don't work: 

```
function roleFromHash(hash: Bytes): string {
  let roleLookupTable = new TypedMap<string,string>();
  roleLookupTable[TOKEN_MANAGER_REVOKE_VESTINGS_ROLE_HASH] = 'CanRevokeVestings'
  return roleLookupTable[hash.toHex()] as string
}
```

Such a function call will fail with `Index signature is missing in type`. 

Right now you have to use `.set(key, value)` and `.get(key)`.

In the future it would be good to support indexing, when we have time to implement it.

**Comment by azf20** [comment]
Closing as stale, please reopen if still valid
