### ISSUE TITLE
`graph init` on `graph-cli-v0.42` fails when adding more than one contract

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-tooling#1135]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Creating a subgraph via `graph init` fails with this error when adding a second contract:
![Screenshot 2023-02-24 at 3 37 44 PM](https://user-images.githubusercontent.com/73024324/221205466-6b2c8a74-4fc3-4715-91bd-80c2286f4fc8.png)

### Reproduction

none

### Steps to Reproduce the Bug or Issue

1. Using graph-cli 0.42, Run `graph init`
2. fill the wizard as follows. 
![Screenshot 2023-02-24 at 3 41 24 PM](https://user-images.githubusercontent.com/73024324/221207007-b74b7234-db84-44ca-acc2-3fabf18ecad1.png)

### Expected behavior

This is an example without errors. Although using one contract.
![Screenshot 2023-02-24 at 3 45 31 PM](https://user-images.githubusercontent.com/73024324/221207759-14c809b2-9f88-4fac-88ff-33d5fcfb4a59.png)

### Platform

- OS: macOS  13.2.1
- NodeJS: v18.12.0
- `@graphprotocol/*` version(s): @graphprotocol/graph-cli": "^0.42.0

**Comment by incrypto32** [comment]
@itsjerryokolo can you try `0.43.0-alpha-20230306074738-d410a35` this version? just do an `npm install @graphprotocol/graph-cli@0.43.0-alpha-20230306074738-d410a35`

**Comment by itsjerryokolo** [comment]
It works. 🎉 
Thanks @incrypto32 
![Screenshot 2023-03-06 at 2 08 46 PM](https://user-images.githubusercontent.com/73024324/223119337-85095d6d-e094-4517-87f8-520cbd8e694b.png)

**Comment by saihaj** [comment]
released [`@graphprotocol/graph-cli@0.42.4`](https://github.com/graphprotocol/graph-tooling/releases/tag/release-1678125024185)
