### ISSUE TITLE
Adding smart contract using 'graph add' leads to SyntaxError with '*Zero*' on manifest: subgraph.yaml

### ISSUE THREAD

**Issue by rishin01** [graphprotocol/graph-tooling#1137]
After using `graph init --product hosted-service` and attempting to add another smart contract using `graph add <Address> --abi <localABI> --contract-name <contractName>`, encountered following error:

```
SyntaxError: Aliased anchor not found: Zero* (4:19)
      2 |       address: '0x8af500dEf828b18A3a5D126F97aDf5D13eE69D3b'
      3 |       abi: lake
    > 4 |       startBlock: *Zero*
```

yaml thinks  `*Zero*` is an alias. I have temporarily fixed the issue by replacing all occurences of `*Zero*` in the node package graph-cli with `0`.

**Comment by incrypto32** [comment]
I think i know what it is.

**Comment by saihaj** [comment]
[@graphprotocol/graph-cli@0.42.3](https://github.com/graphprotocol/graph-tooling/releases/tag/release-1677602776409)
