### ISSUE TITLE
Update Assemblyscript version to ^0.27.1

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-tooling#1187]
- Update Assemblyscript version used in handlers to the latest. May require changes across graph-node, graph-ts, graph-cli, docs

**Comment by saihaj** [comment]
we have this automated PR https://github.com/graphprotocol/graph-tooling/pull/1233 would need to push fixes to this to make CI happy

**Comment by 0237h** [comment]
With #1775, it is now on version [`^0.27.31`](https://github.com/graphprotocol/graph-tooling/commit/7faa3098b2e6c61f09fc81b8b2d333e66b0080d1#diff-b6e999e24ec4287cefcc135097ce205d5319b017a7a1a36b7fd9384158ceeeeeR15).
