### ISSUE TITLE
Call to contract state fails on generated function binding

### ISSUE THREAD

**Issue by VargaElod23** [graphprotocol/graph-tooling#1188]
### Which packages are impacted by your issue?

@graphprotocol/graph-ts

### Describe the issue

Hi guys! I just recently ran into the following error: 
 /Users/vargaelod/taraxa/taraxa-platform/packages/dpos-subgraph/abis/Dpos.json
 The ABI of the contract is attached and used in the codegen. Latest version for the dependency.
However, whenever I try to call a view method like: 

```TypeScript
function getValidatorInfoFromContract(
  validator: Address,
  event: ethereum.Event
): ValidatorBasicInfo {
  let basicInfo = ValidatorBasicInfo.load(validator.toHexString());
  if (!basicInfo) {
    basicInfo = new ValidatorBasicInfo(validator.toHexString());
  }

  const validatorAddress = validator.toHexString();
  const dpos = Dpos.bind(event.address);

  if (validatorAddress) {
    const chainData = dpos.getValidator(validator);

    basicInfo.commission = chainData.commission;
    basicInfo.commissionReward = chainData.commission_reward;
    basicInfo.description = chainData.description;
    basicInfo.totalStake = chainData.total_stake;
    basicInfo.lastCommissionChange = chainData.last_commission_change;
    basicInfo.owner = chainData.owner.toHexString();
    basicInfo.endpoint = chainData.endpoint;
    basicInfo.save();
  }
  return basicInfo;
}
```
The calls fail with:  `RPC error: Error { code: InvalidParams, message: “INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised”, data: None }`

### Reproduction

https://github.com/Taraxa-project/taraxa-platform/tree/feature/add-subgraph-for-dpos/packages/dpos-subgraph

### Steps to Reproduce the Bug or Issue

1. Build
2. Start your local node connected to `mainnet:https://rpc.devnet.taraxa.io`
3. create-local
4. deploy-local

### Expected behavior

As a user, I expect the handler to be able to call the view function, return the data and fill in the entity for the indexing database.

### Platform

- OS: [macOS]
- NodeJS: [v16.10.0]
- "@graphprotocol/graph-cli": "0.42.4"
- "@graphprotocol/graph-ts": "0.29.3"

### Subgraph Manifest

specVersion: 0.0.1
description: Dpos Contract indexing for Taraxa
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: Dpos
    network: mainnet
    source:
      address: "0x00000000000000000000000000000000000000fe"
      abi: Dpos
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - ValidatorBasicInfo
        - ValidatorData
        - UndelegateRequest
        - DelegatorInfo
        - DelegationData
        - UndelegationData
        - CommissionRewardsClaimedEvent
        - CommissionSetEvent
        - DelegatedEvent
        - RedelegatedEvent
        - RewardsClaimedEvent
        - UndelegateCanceledEvent
        - UndelegateConfirmedEvent
        - UndelegatedEvent
        - ValidatorInfoSetEvent
        - ValidatorRegisteredEvent
      abis:
        - name: Dpos
          file: ./abis/Dpos.json
      eventHandlers:
        - event: CommissionRewardsClaimed(indexed address,indexed address)
          handler: handleCommissionRewardsClaimed
        - event: CommissionSet(indexed address,uint16)
          handler: handleCommissionSet
        - event: Delegated(indexed address,indexed address,uint256)
          handler: handleDelegated
        - event: Redelegated(indexed address,indexed address,indexed address,uint256)
          handler: handleRedelegated
        - event: RewardsClaimed(indexed address,indexed address)
          handler: handleRewardsClaimed
        - event: UndelegateCanceled(indexed address,indexed address,uint256)
          handler: handleUndelegateCanceled
        - event: UndelegateConfirmed(indexed address,indexed address,uint256)
          handler: handleUndelegateConfirmed
        - event: Undelegated(indexed address,indexed address,uint256)
          handler: handleUndelegated
        - event: ValidatorInfoSet(indexed address)
          handler: handleValidatorInfoSet
        - event: ValidatorRegistered(indexed address)
          handler: handleValidatorRegistered
      file: ./src/mapping.ts

### Subgraph GraphQL Schema

type ValidatorBasicInfo @entity(immutable: false) {
  id: ID!
  totalStake: BigInt!
  commissionReward: BigInt!
  commission: Int!
  lastCommissionChange: BigInt!
  owner: String!
  description: String!
  endpoint: String!
}

type ValidatorData @entity(immutable: false) {
  id: ID!
  account: String!
  info: ValidatorBasicInfo!
  delegations: [DelegationData!]!
  undelegations: [UndelegationData!]!
}

type DelegationData @entity(immutable: false) {
  id: ID!
  account: String!
  delegator: DelegatorInfo!
  validator: ValidatorData!
}

type UndelegationData @entity(immutable: false) {
  id: ID!
  stake: BigInt!
  block: BigInt!
  validator: ValidatorData!
}

type UndelegateRequest @entity(immutable: false) {
  id: ID!
  eligibleBlockNum: BigInt!
  amount: BigInt!
}

type DelegatorInfo @entity(immutable: false) {
  id: ID!
  stake: BigInt!
  rewards: BigInt!
}

type DelegatedEvent @entity(immutable: true) {
  id: ID!
  delegator: String!
  validator: String!
  amount: BigInt!
}

type UndelegatedEvent @entity(immutable: true) {
  id: ID!
  delegator: String!
  validator: String!
  amount: BigInt!
}

type UndelegateConfirmedEvent @entity(immutable: true) {
  id: ID!
  delegator: String!
  validator: String!
  amount: BigInt!
}

type UndelegateCanceledEvent @entity(immutable: true) {
  id: ID!
  delegator: String!
  validator: String!
  amount: BigInt!
}

type RedelegatedEvent @entity(immutable: true) {
  id: ID!
  delegator: String!
  from: String!
  to: String!
  amount: BigInt!
}

type RewardsClaimedEvent @entity(immutable: true) {
  id: ID!
  account: String!
  validator: String!
}

type CommissionRewardsClaimedEvent @entity(immutable: true) {
  id: ID!
  account: String!
  validator: String!
}

type CommissionSetEvent @entity(immutable: true) {
  id: ID!
  validator: String!
  commission: Int!
}

type ValidatorRegisteredEvent @entity(immutable: true) {
  id: ID!
  validator: String!
}

type ValidatorInfoSetEvent @entity(immutable: true) {
  id: ID!
  validator: String!
}

**Comment by VargaElod23** [comment]
Additional info - using this example via ethers everything works as intended: 

```TypeScript
const contract = new ethers.Contract(dposAddress, Dpos, ethers.provider.getSigner(0));
  const encoded = contract.interface.encodeFunctionData("getValidator", ["0x780fe8b2226cf212c55635de399ee4c2a860810c"]);
  console.log(encoded);
  const call = ethers.provider.call({
    to: dposAddress,
    data: encoded,
  });
  const result = await call;
  const decoded = contract.interface.decodeFunctionResult("getValidator", result);

  console.log(decoded);
```

**Comment by azf20** [comment]
hey @VargaElod23 - I don't know if your null check `if (validatorAddress)` will prevent calling when the `validator` is null, and it looks like the RPC error is complaining that `validator` isn't a valid name / type. Closing for now, you can find more active support in [the Graph discord](https://discord.com/invite/vtvv7FP), please re-open if you believe this is a bug in Graph Node

**Comment by VargaElod23** [comment]
Hi @azf20 . I quadruple-checked and the constraints are fine, in fact, there's no handler where the `validator` isn't a valid Ethereum address. I also added the relevant ABI and you can see that the naming is exactly that + interface can be accessed [here](https://github.com/Taraxa-project/taraxa-evm/blob/master/taraxa/state/dpos/solidity/dpos_contract_interface.sol). I strongly believe this is an error either in the codegen or in the Node itself.

**Comment by VargaElod23** [comment]
Yes, it does, at least for the specified RPC endpoint

**Comment by azf20** [comment]
Why are you running with specVersion 0.0.1, could you try running with 0.0.5?

**Comment by VargaElod23** [comment]
Sure, give me a sec

**Comment by VargaElod23** [comment]
```
graph-graph-node-1  | Mar 14 14:52:39.725 DEBG eth_call, data: 1904bb2e000000000000000000000000780fe8b2226cf212c55635de399ee4c2a860810c, address: 00000000000000000000000000000000000000fe, sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:39.878 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #1) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:40.023 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #2) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:40.164 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #3) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:40.305 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #4) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:40.456 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #5) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:40.619 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #6) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:40.768 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #7) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:40.956 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #8) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:41.119 DEBG Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #9) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:41.311 WARN Trying again after eth_call RPC call for block #1689 (60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4) failed (attempt #10) with result Err(Web3Error(Rpc(Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }))), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:41.334 INFO Done processing trigger, gas_used: 0, data_source: Dpos, handler: handleRewardsClaimed, total_ms: 1694, transaction: 0xcd7b…1d6c, address: 0x0000…00fe, signature: RewardsClaimed(indexed address,indexed address), sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:41.337 INFO Possible reorg detected, retrying, error: failed to process trigger: block #1689 (0x60ef…21e4), transaction cd7bbd9cfd89c46a0c3b07b8d7de8bb41789216bda18e8e8053fc6558ed71d6c: Ethereum node returned an error when calling function "getValidator" of contract "Dpos": RPC error: Error { code: InvalidParams, message: "INVALID_PARAMS: Invalid method parameters (invalid name and/or type) recognised", data: None }
graph-graph-node-1  | wasm backtrace:
graph-graph-node-1  |     0: 0x3594 - <unknown>!src/mapping/getValidatorInfoFromContract

graph-graph-node-1  |     1: 0x39f3 - <unknown>!src/mapping/enforceValidatorDataExists

graph-graph-node-1  |     2: 0x5be0 - <unknown>!src/mapping/handleRewardsClaimed

graph-graph-node-1  | , block_hash: 0x60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4, block_number: 1689, sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:41.346 DEBG Starting or restarting subgraph, sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:41.346 DEBG subscribing to chain head updates, sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: BlockStream

graph-graph-node-1  | Mar 14 14:52:41.485 DEBG Starting block stream, sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

graph-graph-node-1  | Mar 14 14:52:41.500 DEBG Processing 30 triggers, sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: BlockStream

graph-graph-node-1  | Mar 14 14:52:41.500 DEBG 30 candidate triggers in this block, block_hash: 0x60ef0cb669d0f7145066f0d232822f58f5c4d4ca62d00c4858d33e4c878521e4, block_number: 1689, sgd: 1, subgraph_id: QmWiP3Sfr6Pxe6hm2XZDxQRioCgeWCxQax7efzckx6kUoJ, component: SubgraphInstanceManager

```

**Comment by VargaElod23** [comment]
Strange thing is that `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x00000000000000000000000000000000000000FE", "data":"1904bb2e000000000000000000000000780fe8b2226cf212c55635de399ee4c2a860810c"},"latest"],"id":1}' https://rpc.devnet.taraxa.io` works like a charm

**Comment by VargaElod23** [comment]
Yup it seems everything works well from our RPC side @azf20 , the only place the problem can be coming from is the data pinning on the RPC call, it seems.

**Comment by VargaElod23** [comment]
Found the source of the errors in our RPC interface. Thanks @azf20 !
