### ISSUE TITLE
`graph test` command regressions

### ISSUE THREAD

**Issue by dimitrovmaksim** [graphprotocol/graph-tooling#1191]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

It seems there are some regressions in the `graph test` command since `v0.40.0`:

1. The `datasource` argument is made `required`, while it should be optional https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L16
2. `--version`, `-v` options is also marked as required, but it should be optional https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L51
3. It seems the `cachePath` will always point to the default location in the `./tests` folder https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L61-L62, which affects also the version cache https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L72. Specifying another test folder location through the `matchstick.yaml` file will do nothing, because the lookup happens at a later stage here https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L75 and it will always create and save the cache file in the default `./tests` folder instead in the one specified by the config.

### Reproduction

https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/test.ts#L16

### Steps to Reproduce the Bug or Issue

1. Run `graph test` without any arguments using graph-cli `0.42.4`

### Expected behavior

1. `graph test` should run without any arguments
2. First the lookup for a custom test folder from `matchstick.yaml` should happen before setting the `testDir` and `cachePath` and the the lookup for the cached matchstick version

### Screenshots or Videos
1. and 2.
<img width="813" alt="Screenshot 2023-03-16 at 22 42 15" src="https://user-images.githubusercontent.com/20456492/225747986-27c03fe7-74b1-4444-8227-d2dea45604e3.png">

3.
<img width="813" alt="Screenshot 2023-03-16 at 22 52 00" src="https://user-images.githubusercontent.com/20456492/225750543-ad267bf1-ec7b-4173-8ff3-ed152d96e0b4.png">

### Platform

- `@graphprotocol/graph-cli` "0.42.4"

### Additional context

**Comment by dimitrovmaksim** [comment]
Can confirm the datasource and the version issue seem to be fixed

**Comment by saihaj** [comment]
fixed `3` too @dimitrovmaksim you can try `@graphprotocol/graph-cli@0.43.1-alpha-20230321032415-91f97ff`
