### ISSUE TITLE
`zksync-era` is only a studio option

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1200]
Need to remove `zksync-era` as an option from Hosted Service option list. 

Issue is today the https://github.com/graphprotocol/graph-tooling/blob/876bc523e5a53db162d9b5aa79e9de76a9e92ccf/packages/cli/src/protocols/index.ts#L76-L77 is shared between both and we need to refactor to make it based on the service

**Comment by alex-pakalniskis** [comment]
Legacy work (likely wont/doesnt neet to happen), but related to decoupling Studio & CLI
