### ISSUE TITLE
Fetching start block slowly and can not to skip

### ISSUE THREAD

**Issue by amehito** [graphprotocol/graph-tooling#1282]
### Bug report

When init a subgraph, process is okay until **Fetch Start Block**, which takes such a long time and eventually get failed.

✖ Failed to fetch Start Block: Failed to fetch contract creation transaction hash

After that, subgraph scaffold have been created successfully, so I mean, if this process is not necessary, can I just get an option to skip it 

### Relevant log output

```Shell
/
```

### IPFS hash

/

### Subgraph name or link to explorer

/

### Some information to help us out

- [ ] Tick this box if this bug is caused by a regression found in the latest release.
- [ ] Tick this box if this bug is specific to the hosted service.
- [X] I have searched the issue tracker to make sure this issue is not a duplicate.

### OS information

macOS

**Comment by azf20** [comment]
transferred from graph-node, as I think this relates to tooling - @amehito what network are you using where you see this timeout? cc @incrypto32 who I think worked on the start block fetching for info

**Comment by incrypto32** [comment]
@amehito it depends on the chain you are on. If the chain has an etherscan instance and API support the start block fetching works, else it throws an error and move on to the next step. You can always skip this step by manually specifying --start-block

**Comment by azf20** [comment]
thanks @incrypto32 , closing for now, @amehito please re-open if that doesn't resolve the issue
