### ISSUE TITLE
Moving from 0.34.0 to 0.47.0, issue with default values

### ISSUE THREAD

**Issue by vrde** [graphprotocol/graph-tooling#1310]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

:wave: I've upgraded from `0.34.0` to `0.47.0`. I noticed that the generated schemas are now missing the default values, see example below

## 0.34.0

```javascript
export class Resolution extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));

    this.set("snapshotId", Value.fromBigInt(BigInt.zero()));
    this.set("ipfsDataURI", Value.fromString(""));
    this.set("isNegative", Value.fromBoolean(false));
    this.set("yesVotesTotal", Value.fromBigInt(BigInt.zero()));
    this.set("resolutionType", Value.fromString(""));
    this.set("createTimestamp", Value.fromBigInt(BigInt.zero()));
    this.set("updateTimestamp", Value.fromBigInt(BigInt.zero()));
    this.set("approveTimestamp", Value.fromBigInt(BigInt.zero()));
    this.set("rejectTimestamp", Value.fromBigInt(BigInt.zero()));
    this.set("createBy", Value.fromBytes(Bytes.empty()));
    this.set("voters", Value.fromStringArray(new Array(0)));
    this.set("hasQuorum", Value.fromBoolean(false));
    this.set("executionTo", Value.fromBytesArray(new Array(0)));
    this.set("executionData", Value.fromBytesArray(new Array(0)));
  }

  // ...
```
Source: https://github.com/NeokingdomDAO/subgraph/blob/89a6068b0437ef75ed2b1242e5d94f0300747074/dao/generated/schema.ts#L182-L201

## 0.47.0

```javascript
export class Resolution extends Entity {
  constructor(id: string) {
    super();
    this.set("id", Value.fromString(id));
  }

  // ...
```

Source: https://github.com/NeokingdomDAO/subgraph/blob/23970e8ace0d061317026a128fa7bfc25c3ed9c2/dao/generated/schema.ts#L216-L220

## Question

Is there any flag I need to pass to the generator to create the missing default values?

### Reproduction

https://github.com/NeokingdomDAO/contracts

### Steps to Reproduce the Bug or Issue

1. Clone the repo
2. Run `codegen`
3. Check the generated code.

### Expected behavior

The version I used before to generate the schema included initialization with default values. Now it doesn't do it anymore. I would expect one of the following thing:

- add a flag in the generator to enable the creation of the default values; or
- make the generator work as before.

### Platform

- OS: Linux
- NodeJS: 18
- "dependencies": {
    "@graphprotocol/graph-cli": "0.47.2",
    "@graphprotocol/graph-ts": "0.29.3"
  }

**Comment by dimitrovmaksim** [comment]
Thus has been answered on Discord. I suppose the issue can be closed.
