### ISSUE TITLE
npm install -g @graphprotocol/graph-cli@latest error

### ISSUE THREAD

**Issue by bingdianchen** [graphprotocol/graph-tooling#1344]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

I am unable to upgrade and install @graphprotocol/graph-cli
`npm install -g @graphprotocol/graph-cli@latest` error
An error was also reported using yarn
Installing with a new machine is also incorrect

### Reproduction

@graphprotocol/graph-cli

### Steps to Reproduce the Bug or Issue

1.npm install -g @graphprotocol/graph-cli
2.npm install -g @graphprotocol/graph-cli@latest
3.yarn global upgrade @graphprotocol/graph-cli

### Expected behavior

I hope it can be used normally

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/20591947/236615219-3d9e2289-2cd1-4d8f-b2ad-da2175689bea.png)
![image](https://user-images.githubusercontent.com/20591947/236615262-36e50a7a-5607-4f08-b8bc-510c81fc48de.png)
![image](https://user-images.githubusercontent.com/20591947/236615664-ca805a78-82f1-44ae-8fb7-1929b8e0bdbf.png)

### Platform

- OS: [Linux]
- NodeJS: [v16.15.0]
- @graphprotocol/graph-cli/0.48.0 linux-x64 node-v16.15.0

**Comment by llopez** [comment]
I am experiencing a similar problem.

```
yarn global add @graphprotocol/graph-cli              
yarn global v1.22.19
[1/4] Resolving packages...
warning @graphprotocol/graph-cli > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning @graphprotocol/graph-cli > ipfs-http-client > multiaddr@10.0.1: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > ipfs-core-types > multiaddr@10.0.1: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > ipfs-core-utils > multiaddr@10.0.1: This module is deprecated, please upgrade to @multiformats/multiaddr
warning @graphprotocol/graph-cli > ipfs-http-client > ipfs-core-utils > multiaddr-to-uri@8.0.0: This module is deprecated, please upgrade to @multiformats/multiaddr-to-uri
warning @graphprotocol/graph-cli > ipfs-http-client > ipfs-core-utils > multiaddr-to-uri > multiaddr@10.0.1: This module is deprecated, please upgrade to @multiformats/multiaddr
error Command failed.
Exit code: 1
Command: git
Arguments: pull
Directory: /home/luis/.cache/yarn/v6/.tmp/166c4037ddf7608d79e84e263dcd7746
Output:
Your configuration specifies to merge with the ref 'refs/heads/master'
from the remote, but no such ref was fetched.
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by saihaj** [comment]
These are issues with your local cache, @llopez in your case it is `yarn cache clean --all` for @bingdianchen try `npm cache clean –force` . Also woth `rm -rf node_modules`
