### ISSUE TITLE
Library file 'microevent.ts' not found.

### ISSUE THREAD

**Issue by yoratoni** [graphprotocol/graph-tooling#1345]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Note: This bug seems to only appear on Windows, I tried with the same environment on Ubuntu, it worked file.

When trying to build a subgraph, this error appears:
`Library file 'microevent.ts' not found.`.

I tried to trace back the issue a bit:

It seems to be linked to AssemblyScript and the custom defined libs at line 626 - 646 in:
`node_modules/@graphprotocol/graph-cli/node_modules/assemblyscript/cli/asc.js`.

At line 643 inside of that file, it tries to read the `microevent.ts` library as a file with fs.readFileSync() inside of the node_modules, so of course, it returns null and prints the error.

### Reproduction

www.thegraph.com

### Steps to Reproduce the Bug or Issue

1. Cloning an existing subgraph
2. yarn install etc..
3. Run the `codegen` command.
4. Run the `build` command.

### Expected behavior

Expected the subgraph to build fine.

### Platform

- OS: Windows 10
- NodeJS: 16.20.0
- `@graphprotocol/graph-cli` version: 0.49.0
- `@graphprotocol/graph-ts` version: 0.30.0

**Comment by Corantin** [comment]
Bump

**Comment by Corantin** [comment]
Did you found any workaround? :)

**Comment by yoratoni** [comment]
> Did you found any workaround? :)

Yeah, I switched to a sublinux environment (WSL) ^^

**Comment by yoratoni** [comment]
> @Corantin @yoratoni to confirm this is an issue only on Windows 10?

Yeah definitely, I switched to WSL after not being able to solve the issue and it works perfectly fine now.

**Comment by Corantin** [comment]
I'm on Linux now and dont have the problem
