### ISSUE TITLE
`graph init` wrongly initialises Polygon ZkEvm Testnet 

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-tooling#1354]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Polygon ZkEvm Testnet is not yet supported by The Graph, but this network is available on the graph-cli can be successfully initialised like we support it. This results in error during deployment.

### Reproduction

nil

### Steps to Reproduce the Bug or Issue

<img width="693" alt="Screenshot 2023-05-21 at 10 43 08 AM" src="https://github.com/graphprotocol/graph-tooling/assets/73024324/3e5220ad-f1be-4049-a24b-75116414e468">

### Expected behavior

Probably have the network hidden temporarily, or throw an error that indicates the network isn't supported

### Platform

- OS: macOS 13.3.1
- NodeJS: v18.16.0
-  "@graphprotocol/graph-cli": "0.49.0",
    "@graphprotocol/graph-ts": "0.29.1"

**Comment by alex-pakalniskis** [comment]
The Graph supports Polygon zkEVM now: https://thegraph.com/networks/polygon-zk-evm/?subnetwork=polygon-zk-evm-mainnet
