### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by ramzanthegreat** [graphprotocol/graph-tooling#1365]
### Which packages are impacted by your issue?

@graphprotocol/graph-ts

### Describe the issue

When I run `npm run build` I'm getting the following error:
```
./node_modules/.pnpm/@graphprotocol+graph-ts@0.31.0/node_modules/@graphprotocol/graph-ts/chain/arweave.ts:28:25
Type error: Cannot find name 'u64'.

  26 |   export class Block {
  27 |     constructor(
> 28 |       public timestamp: u64,
     |                         ^
  29 |       public lastRetarget: u64,
  30 |       public height: u64,
  31 |       public indepHash: Bytes,
  ```

### Reproduction

Private repo

### Steps to Reproduce the Bug or Issue

Private repo so can't share the code

### Expected behavior

Expected build to be successful 

### Platform

- OS: [e.g. macOS]
- NodeJS: [18.5.0]
- @graphprotocol/graph-ts": "^0.31.0"

**Comment by saihaj** [comment]
Can you create a [minimal reproduction](https://en.wikipedia.org/wiki/Minimal_working_example)?
