### ISSUE TITLE
use of the deprecated `ipfs-http-client` dependency

### ISSUE THREAD

**Issue by julien-devatom** [graphprotocol/graph-tooling#1446]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

The package ipfs-http-client is deprecated (see [this issue for migration process](https://github.com/ipfs/js-ipfs/issues/4336))

### Reproduction

_ 

### Steps to Reproduce the Bug or Issue

_

### Expected behavior

_

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `@graphprotocol/*` version(s): [e.g. 2.6.2]

**Comment by chikchoi6** [comment]
Any update ?

**Comment by saihaj** [comment]
do you want to send a PR @chikchoi6?

**Comment by YaroShkvorets** [comment]
Removed in 0.93
