### ISSUE TITLE
increasing timeouts and more retries for external API calls

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1447]
> Observation from the ETH Accra hackathon: Internet is not very stable and during init, there are some points where the CLI is doing some API calls which timed out: Download ABI from Etherscan and resolving start-block. Can we make these more resilient? Longer time-out windows and automatic retries?
from @schmidsi

**Comment by YaroShkvorets** [comment]
Main issue is with Etherscan 5 second rate limits. This causes every initial block query to fail which is kinda annoying.
This PR allows to retry: https://github.com/graphprotocol/graph-tooling/pull/1491
