### ISSUE TITLE
Using `derivedFrom` on Interfaces failing with `Cannot read properties of undefined (reading 'fields')` on `graph-cli 0.57`

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-tooling#1449]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Using `derivedFrom` on Interfaces failing with `Cannot read properties of undefined (reading 'fields')` on `graph-cli 0.57`

<img width="641" alt="Screenshot 2023-09-08 at 3 21 07 PM" src="https://github.com/graphprotocol/graph-tooling/assets/73024324/3a87f46c-b0b0-406a-aee9-c727b0028f6d">

I've attached the relevant lines on the github links below:

https://github.com/wighawag/conquest-graph/blob/06b6e04480bdd227c2e93b049af7c885a60815f4/schema.graphql#L172
https://github.com/wighawag/conquest-graph/blob/06b6e04480bdd227c2e93b049af7c885a60815f4/schema.graphql#L149C12-L149C22

This currently works on cli version `0.51.2`

### Reproduction

https://github.com/wighawag/conquest-graph

### Steps to Reproduce the Bug or Issue

Clone the repo below, install `graph cli 0.57.0` and run `graph  codegen`

https://github.com/wighawag/conquest-graph

### Expected behavior

codegen shouldn't fail

### Platform

nil

**Comment by azf20** [comment]
thanks @itsjerryokolo! @saihaj looks like this is a regression?

**Comment by dimitrovmaksim** [comment]
It seems it's broken since v0.53.0

**Comment by dimitrovmaksim** [comment]
There seems to be another issue with Interfaces. Codegen does not generate a class/type for the interface in `generated/schemat.ts`

```graphql
interface IExample {
  id: ID! 
  main: Main!
  num: Int!
}

type Example1 implements IExample @entity {
  id: ID! 
  main: Main!
  num: Int!
}

type Main @entity {
  id: ID!
  examples: [IExample!]! @derivedFrom(field: "main")
}
```

will generate the following loader for `main.examples.load()`

```ts
export class IExampleLoader extends Entity {
  _entity: string;
  _field: string;
  _id: string;

  constructor(entity: string, id: string, field: string) {
    super();
    this._entity = entity;
    this._id = id;
    this._field = field;
  }

  load(): IExample[] {
    let value = store.loadRelated(this._entity, this._id, this._field);
    return changetype<IExample[]>(value);
  }
}
```

But `IExample` does not exist as type

![Screenshot 2023-09-15 at 13 10 47](https://github.com/graphprotocol/graph-tooling/assets/20456492/76a12725-d475-4272-8eeb-7d17a0f4ff5b)

which results in 

```sh
ERROR TS2304: Cannot find name 'IExample'.

   load(): IExample[] {
           ~~~~~~~~
 in generated/schema.ts(6982,11)
```

**Comment by 0xged** [comment]
Same happening to me on [our subgraph](https://github.com/mean-finance/dca-subgraph/) - steps to reproduce it's just to update the `cli` version and try to build. Also subscribing to know when this is getting fixed. 🚀
