### ISSUE TITLE
Do not create `.git` folder after running `graph init`

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-tooling#1450]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

One of the main developer journeys into The Graph is adding a subgraph into an existing repository. This journey is also very often followed at hackathons. When developers run `graph init`, by default the command generates a git repository.

If the subgraph is initialised in an existing git repository, it is seen as a submodule and excluded from the parent git repository. This is most of the time not intended and confusing. At hackathons, we see a lot of hacker submitting their project without the subgraph code in there.

### Reproduction

https://github.com/schmidsi/graph-cli-git-problem/tree/main/packages

### Steps to Reproduce the Bug or Issue

1. Create a project (any mono-repo setup)
2. Add a subgraph with `graph init`
3. Try to add this subgraph to git

### Expected behavior

As a developer, I expect that `graph init` does not create a git repo.

### Platform

- OS: MacOS MGQ46P7CFL
- NodeJS: v18.15.0
- `@graphprotocol/graph-cli` version(s): @graphprotocol/graph-cli/0.57.0 darwin-arm64 node-v18.15.0

**Comment by schmidsi** [comment]
This might be related: https://github.com/graphprotocol/graph-tooling/issues/775

In general, I think the CLI should be source control agnostic. That being said, a `.gitignore` file might be usable.

**Comment by azf20** [comment]
@schmidsi agree that this can be counterintuitive - and I think often subgraph code will be a part of a larger repository. Maybe the command could detect whether it is being called in an existing repository, and give the developer a choice?

**Comment by dimitrovmaksim** [comment]
There's a git command that can be used to check the current location is in a git repo `git rev-parse --is-inside-work-tree` or `git rev-parse --is-inside-git-dir`
