### ISSUE TITLE
`--protocol` flag breaks `graph init` with `TypeError: Cannot read properties of undefined (reading 'contract')`

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/graph-tooling#1472]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

When initialising a new contract using `graph init` on `graph cli: 0.58`, adding a --protocol flag breaks the initialisation process. 

### Reproduction

nil

### Steps to Reproduce the Bug or Issue

Run this command `graph init --from-contract 0xc9fe4ffc4be41d93a1a7189975cd360504ee361a --protocol ethereum  --network mainnet --contract-name Token --index-events`

It breaks with the error below when you add the `--protocol` and `--network` flags
<img width="787" alt="Screenshot 2023-10-02 at 12 51 43 PM" src="https://github.com/graphprotocol/graph-tooling/assets/73024324/cbe14bec-dd60-496a-8205-a949ed50862b">

### Expected behavior

<img width="432" alt="Screenshot 2023-10-02 at 12 57 05 PM" src="https://github.com/graphprotocol/graph-tooling/assets/73024324/aedd96a3-5869-4ccf-896c-4dfb0ed7ea12">

Network should be pulled from the network flag instead of displaying `undefined network: mainnet`

<img width="429" alt="Screenshot 2023-10-02 at 12 57 42 PM" src="https://github.com/graphprotocol/graph-tooling/assets/73024324/a063709b-10d0-465f-bee8-9e839f15b9b5">

### Platform

@graphprotocol/graph-cli/0.58.0 darwin-arm64 node-v18.16.0

**Comment by azf20** [comment]
@itsjerryokolo do you see the same issue if you don't pass `protocol`?

**Comment by itsjerryokolo** [comment]
@azf20 No, just running `graph init`, and following the prompt, works.

**Comment by azf20** [comment]
right if you run:

```
graph init --from-contract 0xc9fe4ffc4be41d93a1a7189975cd360504ee361a  --network mainnet --contract-name Token --index-events
```

i.e. without the `protocol` flag (but with the network flag)
