### ISSUE TITLE
License conflict

### ISSUE THREAD

**Issue by YaroShkvorets** [graphprotocol/graph-tooling#1525]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

I'm no license expert, but it appears that `web3-eth-abi` dependency licensed under LGPL-3, might be incompatible with MIT license. Just a heads-up.

### Reproduction

N/A

### Steps to Reproduce the Bug or Issue

N/A

### Expected behavior

N/A

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `@graphprotocol/*` version(s): [e.g. 2.6.2]

**Comment by azf20** [comment]
I am also not a license expert, but I can't find any sources which suggest that an MIT project can't have an LGPL-3 dependency (assuming no modifications). Did you find something to the contrary @YaroShkvorets ?

**Comment by YaroShkvorets** [comment]
I got this warning from fossa.com tool: https://fossa.com
But looks like you are right, shouldn't be an issue.

**Comment by azf20** [comment]
got it - thanks for taking a look!
