### ISSUE TITLE
When adding a second contract if abi fetching fails, it exits and gives no further options.

### ISSUE THREAD

**Issue by HareemSaad** [graphprotocol/graph-tooling#1560]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

When initializing a subgraph, I need to provide two contracts that are both verified on Sepolia. I can add the first one without any issues. However, when adding the second one, after entering the address and providing the contract name, the ABI fetching process consistently fails. Instead of prompting for a retry or a local path, it simply exits.

### Reproduction

N/A (private)

### Steps to Reproduce the Bug or Issue

1. Add First Contract
2. Say yes to adding another contract
3. Add the second contract's address
4. Enter the second contract's name
5. No prompt just exists

### Expected behavior

I expected retry prompts or to add abi locally, in actuality it just exit.

### Screenshots or Videos

![Screenshot from 2024-01-14 07-28-32](https://github.com/graphprotocol/graph-tooling/assets/88980688/0db125bc-c748-4758-8ccf-8c454428ea34)

### Platform

- OS: Linux 23
- NodeJS: 21.4.0
- The Graph CLI (graph-cli): 0.65.0

**Comment by 0237h** [comment]
Fixed by #1766
