### ISSUE TITLE
Subgraph initialisation failed due to: git commit -m "Initialize subgraph"

### ISSUE THREAD

**Issue by shantanu-bico** [graphprotocol/graph-tooling#1565]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Upon initialising a subgraph (hosted-service), the initialisation broke with the following trace:
✖ Failed to fetch Start Block: Failed to fetch contract creation transaction hash
✔ Do you want to retry? (Y/n) · true
✔ Fetching Start Block
✔ Start Block · 17025946
✔ Contract Name · Contract
✔ Index contract events as entities (Y/n) · true
  Generate subgraph
  Write subgraph to directory
✔ Create subgraph scaffold
✔ Initialize networks config
✖ Failed to initialize subgraph repository: Command failed: git commit -m "Initialize subgraph"

    Error: Command failed: git commit -m "Initialize subgraph"

    Code: 1

For context, I have git initialised in my cli and setup appropriately, my git cli version is "git version 2.39.3 (Apple Git-145)"

For further context, here is the version of graph and node cli that I am using: 
graph --version
@graphprotocol/graph-cli/0.66.0 darwin-arm64 node-v21.2.0

### Reproduction

There is no repo yet, I am stuck at the first step of initilisation

### Steps to Reproduce the Bug or Issue

Upon following the default steps at Initialising a hosted service subgraph, the first step to `graph init` is causing this issue for me.
It isn't my first subgraph but this error started occuring randomly.

The command I ran: graph init --product hosted-service shantanu-bico/sa-v1-factory-ethereum
The output trace recieved:
✔ Ethereum network · mainnet
✔ Contract address · 0x000000f9ee1842bb72f6bbdd75e6d3d4e3e9594c
✔ Fetching ABI from Etherscan
✖ Failed to fetch Start Block: Failed to fetch contract creation transaction hash
✔ Do you want to retry? (Y/n) · true
✖ Failed to fetch Start Block: Failed to fetch contract creation transaction hash
✔ Do you want to retry? (Y/n) · true
✔ Fetching Start Block
✔ Start Block · 17025946
✔ Contract Name · Contract
✔ Index contract events as entities (Y/n) · true
  Generate subgraph
  Write subgraph to directory
✔ Create subgraph scaffold
✔ Initialize networks config
✖ Failed to initialize subgraph repository: Command failed: git commit -m "Initialize subgraph"

    Error: Command failed: git commit -m "Initialize subgraph"

    Code: 1

### Expected behavior

I expect the graph to be initialised

### Platform

- MacOS
@graphprotocol/graph-cli/0.66.0 darwin-arm64 node-v21.2.0

**Comment by saihaj** [comment]
do you have `git installed`?

**Comment by shantanu-bico** [comment]
Yes @saihaj , I do, as I mentioned the git cli version is "git version 2.39.3 (Apple Git-145)"
And also, this issue is new, I have developed and deployed multiple subgraphs before.

**Comment by saihaj** [comment]
hmm so to unblock you try `graph init --skip-git`. That should let you `init` a subgraph.

I am curious why `git commit` is failing there isn't any detailed error. Can you try running `DEBUG=graph-cli:* graph init` and then we can see if there are more useful logs

**Comment by shantanu-bico** [comment]
Yes, adding `--skip-git` worked.
Here are the logs you requested:
  graph-cli:protocol Available networks {"arweave":["arweave-mainnet"],"ethereum":["mainnet","rinkeby","goerli","poa-core","poa-sokol","gnosis","matic","mumbai","fantom","fantom-testnet","bsc","chapel","clover","avalanche","fuji","celo","celo-alfajores","fuse","moonbeam","moonriver","mbase","arbitrum-one","arbitrum-goerli","arbitrum-sepolia","optimism","optimism-goerli","aurora","aurora-testnet","base-testnet","base","zksync-era","zksync-era-testnet","sepolia","polygon-zkevm-testnet","polygon-zkevm","scroll-sepolia","scroll"],"near":["near-mainnet","near-testnet"],"cosmos":["cosmoshub-4","theta-testnet-001","osmosis-1","osmo-test-4","juno-1","uni-3"],"substreams":["mainnet"]} +0ms
 ›   Warning: In next major version, this flag will be removed. By default we will deploy to the Graph Studio. Learn more about Sunrise of 
 ›   Decentralized Data https://thegraph.com/blog/unveiling-updated-sunrise-decentralized-data/
 ›   Warning: In next major version, this flag will be removed. By default we will stop initializing a Git repository.
  graph-cli:commands:init Flags: {
  graph-cli:commands:init   'allow-simple-name': false,
  graph-cli:commands:init   'skip-install': false,
  graph-cli:commands:init   'skip-git': false
  graph-cli:commands:init } +0ms

**Comment by saihaj** [comment]
@shantanu-bico I added some more debug logs around the `git init` flow. Can you try running this version [`0.67.3-alpha-20240124142956-af00244` ](https://github.com/graphprotocol/graph-tooling/pull/1574#issuecomment-1908245354) with the debug flag?
