### ISSUE TITLE
CLI exits with 0 even when graph deploy has failed

### ISSUE THREAD

**Issue by jaybuidl** [graphprotocol/graph-tooling#1570]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

If `graph deploy` fails, it should exit with 1, so that the error can be reported or handled in a CI context (e.g. Github workflow), but it exits with 0 currently.

### Reproduction

https://github.com/kleros/kleros-v2/actions/runs/7578013905/job/20639879509#step:13:120

### Steps to Reproduce the Bug or Issue

1. Run `graph deploy --studio -l existingLabel` 
2. Run `echo $?`

![image](https://github.com/graphprotocol/graph-client/assets/22213980/06a0ee07-5cad-47af-a183-c922e08a4bc6)

### Expected behavior

If `graph deploy` fails, it should exit with 1, so that the error can be reported or handled in a CI context (e.g. Github workflow)

### Platform

- OS: macOS
- NodeJS: 16.20.2
- `@graphprotocol/graph-cli` version(s): [0.64.1]

### Additional context

I have only looked at `graph deploy` with Studio, but other products or sub-commands might be affected too.

**Comment by saihaj** [comment]
One more report on Discord https://discord.com/channels/438038660412342282/438070183794573313/1207010623297290320

**Comment by JamesEarle** [comment]
> One more report on Discord https://discord.com/channels/438038660412342282/438070183794573313/1207010623297290320

This was me, so I'm adding more information here.

Calling to

```bash
$ yarn graph deploy --studio <slug> --deploy-key <key> --version-label <label>
```
using a `<label>` that already exists will fail the deploy process 

```bash
Build completed: QmcyuNXAXyBsFyk2buzzDxLUc8NTsws5SYAxRbGX8hDPmK

✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Version label already exists.
UNCAUGHT EXCEPTION: Error: EEXIT: 1
Done in 17.07s.
```

but when I call to check the exit code of that, it shows 0

```bash
$ echo $?
0
```

Currently I'm using 
```bash
$ yarn -v
1.22.19
```

with the graph packages in my package.json as

```
    "@graphprotocol/graph-cli": "^0.61.0",
    "@graphprotocol/graph-ts": "0.30.0",
```

**Comment by mliu** [comment]
+1 This is also affecting our CI/CD pipelines. Did you find a workaround?

**Comment by clemsos** [comment]
+1 same issue here

**Comment by DJercic** [comment]
+1, same issue
