### ISSUE TITLE
"Mainnet" term for "Ethereum Mainnet" not self explanatory when initializing a subgraph 

### ISSUE THREAD

**Issue by joellutterodt** [graphprotocol/graph-tooling#1577]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

When initializing a subgraph on the Ethereum Mainnet, it's a bit confusing for beginners to know what to select next because of the "mainnet" term if they want to select the "Ethereum Mainnnet". Based on the fact that it takes you to be familiar with the ecosystem before you can easily guess the "Mainnet" in the set of options is referring to the "Ethereum Mainnet"

### Reproduction

VS code cli

### Steps to Reproduce the Bug or Issue

1. Initialize the graph init
2. Select Protocol
3. Give subgraph slug name
4. Select directly to create the subgraph
5. Prompt to select the network to use --- where the bug is "mainnet"

### Expected behavior

As a user, I expected "Ethereum Mainnet" instead of "mainnet"

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `@graphprotocol/*` version(s): [e.g. 2.6.2]

**Comment by schmidsi** [comment]
Yes, I observe that this is confusing especially folks not very familiar with the Ethereum ecosystem. Also, the protocol should probably be EVM?

**Comment by joellutterodt** [comment]
Yes, the protocol should be EVM to be more self explainatory

**Comment by YaroShkvorets** [comment]
Solved in 0.93
