### ISSUE TITLE
Blast-Sepolia

### ISSUE THREAD

**Issue by andreibadea20** [graphprotocol/graph-tooling#1586]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

I can't find the blast-sepolia network when I run graph init 
![graph-init](https://github.com/graphprotocol/graph-tooling/assets/105772011/fead4d34-e411-4d2b-9977-7099d31cc1dc)

### Reproduction

-

### Steps to Reproduce the Bug or Issue

1. Check version of graph-cli
2. run graph init
3.  try to find the blast-sepolia

### Expected behavior

Can't see the network

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `@graphprotocol/*` version(s): [e.g. 2.6.2]

**Comment by saihaj** [comment]
it is named `blast-testnet`
