### ISSUE TITLE
Error: Unable to fetch available networks from API

### ISSUE THREAD

**Issue by Luyunee** [graphprotocol/graph-tooling#1597]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

The error is super clear inside the picture below:
<img width="650" alt="572866b59b7d8ae4ded11ec64d8d2f1" src="https://github.com/graphprotocol/graph-tooling/assets/150660295/6bf06752-6526-40a0-92a0-aaef0921e743">

And the i tried adding "--network sepolia" as it mentioned and it ended up with another error:
<img width="623" alt="51159c5d30a8efd6bd2e18877c2eec1" src="https://github.com/graphprotocol/graph-tooling/assets/150660295/acae32c2-7f75-4424-8987-fc95bfb47ed6">

Then i added "--from-contract" flag and it came up with the first error again:
<img width="678" alt="35ca7f97a037200b38e02ca5f416c3b" src="https://github.com/graphprotocol/graph-tooling/assets/150660295/055a5e2b-114b-4d50-98d5-b2a4db78d0b5">

 

### Reproduction

vs code CLI

### Steps to Reproduce the Bug or Issue

1. Initialize the graph init
2. Select Protocol
3. Give subgraph slug name
4. Hit "Enter" and then the error pops up

### Expected behavior

I should see a list of networks i can opt in right after i gave subgraph slug name.

### Screenshots or Videos

Screenshots have been posted in the describtion section.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `@graphprotocol/*` version(s): [e.g. 2.6.2]

**Comment by saihaj** [comment]
are you using a VPN?

**Comment by Luyunee** [comment]
I fixed it by updating Nodejs to the latest version
