### ISSUE TITLE
generate `docker-compose.yml` with `graph init`

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1602]
### Discussed in https://github.com/graphprotocol/graph-tooling/discussions/1599

<div type='discussions-op-text'>

<sup>Originally posted by **schmidsi** February 29, 2024</sup>
In oder to incentivise more local development, I think it would be nice to have a `docker-compose.yml` file automatically generated during `graph init`. I think the [one in the graph-node repo](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml) is pretty good.

`dev` and `clean` commands as described here: https://github.com/schmidsi/hackathon-starterkit/blob/main/package.json#L3 might be good.

I think best would be to only add it if it is selected during the `init` dialog. Similar to:

```
✔ Generate ABI and schema types with yarn codegen
```

And enable it by default. Thoughts?

</div>

**Comment by yehia67** [comment]
Hi @saihaj,
Can I help?
I did a quick check, I see I need to understand the [init.ts](https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/commands/init.ts) file to know how to add the [docker-compose.yml](https://github.com/graphprotocol/graph-node/blob/master/docker/docker-compose.yml) file to it

**Comment by saihaj** [comment]
assigned it to you @yehia67 lmk if you have any questions

**Comment by yehia67** [comment]
Hi @saihaj,
I've made the changes as discussed. However, I was unable to test them. I attempted to use `pnpm link --global` followed by `pnpm link graphprotocol-tools-monorepo`, but this approach did not work. Is this the standard testing method, or should I consider an alternative approach?

**Comment by saihaj** [comment]
> Hi @saihaj, I've made the changes as discussed. However, I was unable to test them. I attempted to use `pnpm link --global` followed by `pnpm link graphprotocol-tools-monorepo`, but this approach did not work. Is this the standard testing method, or should I consider an alternative approach?

they way I test things I setup a project and then have following `package.json` 

```json
{
  "scripts": {
    "codegen": "graph codegen",
    "build": "graph build",
  },
  "dependencies": {
    "@graphprotocol/graph-cli": "file:/Users/saihaj/Desktop/thegraph/graph-tooling/packages/cli",
    "@graphprotocol/graph-ts": "file:/Users/saihaj/Desktop/thegraph/graph-tooling/packages/ts"
  }
}
```

**Comment by yehia67** [comment]
Hi @saihaj,
I just submitted a PR #1610 if you need any change please let me know, Thank you 😄

**Comment by saihaj** [comment]
[@graphprotocol/graph-cli@0.69.0](https://github.com/graphprotocol/graph-tooling/releases/tag/%40graphprotocol%2Fgraph-cli%400.69.0)
