### ISSUE TITLE
Adding second contract fails if contract is not verified.

### ISSUE THREAD

**Issue by gotnoshoeson** [graphprotocol/graph-tooling#1607]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Came upon this bug at ETHDenver @kmjones1979

When running graph init I am able to add a smart contract that is not verified by providing a file path for the ABI. Then there is a prompt to add another contract. If the contract is not verified, the etherscan verify fails and the program exits but DOESN'T have an option to provide a file path for the ABI like the first contract did.

I also tried to "graph add <CONTRACT_ADDRESS>", but it also exited when it wasn't able to etherscan verify.

### Reproduction

https://github.com/gotnoshoeson/FanSocietyv2

### Steps to Reproduce the Bug or Issue

1. Run 'graph init --studio <SUBGRAPH_SLUG>' and follow the prompts to add the first contract 2. There will be a prompt to add another contract, select 'Yes'. 3. Follow the prompt and provide a contract address that has NOT been verified on etherscan.

### Expected behavior

As a user, I was expecting that once the second contract verification failed I would be able to provide a file path for the ABI. This is how the tool works for the first contract.

### Platform

- OS:  macOS
- NodeJS: v20.8.0
- @graphprotocol/graph-cli/0.68.4 darwin-x64 node-v20.8.0

**Comment by 0237h** [comment]
Fixed by #1766
