### ISSUE TITLE
graphCLI using the wrong endpoint for etherscan ethereum

### ISSUE THREAD

**Issue by dibolero** [graphprotocol/graph-tooling#1608]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

After installing the graph using the following command

```npm install @graphprotocol/graph-cli```
And then running graph init, it gets stuck at the contract verification part because the package seems to be using the wrong URL. 

The error I see

`Failed to fetch ABI from Etherscan: getaddrinfo ENOTFOUND api-ethereum_network.etherscan.io`

It should be using api.etherscan.io instead. 

### Reproduction

local

### Steps to Reproduce the Bug or Issue

1. Install @graphprotocol/graph-cli
2. Run graph init --product subgraph-studio --from-contract <contract> --network ETHEREUM_NETWORK <slug>

### Expected behavior

Expecting the self-service steps to find the ABI of the contract on Ethereum. 

### Platform

- OS: [e.g. macOS]
- NodeJS: [e.g. 20.10.0]
- `@graphprotocol/` version:10.2.3

**Comment by saihaj** [comment]
`ETHEREUM_NETWORK` is not a valid option.  You can go through the wizard to see all possible options
