### ISSUE TITLE
Order list of evm chains in `graph init`

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1618]
make `ethereum-mainnet` the first and then alphabetically order rest of the chains.

**Comment by joshuanazareth97** [comment]
Can I pick this issue if it isn't being worked on?

**Comment by saihaj** [comment]
@joshuanazareth97 go for it! Feel free to ping me here for any questions navigating the codebase.

**Comment by maoueh** [comment]
@joshuanazareth97 Fork the repository to your own version and push your branch to your own fork. You can then open a PR here that ask to merge your's branch fork into this repository.

**Comment by maoueh** [comment]
@joshuanazareth97 Here some useful links if you never done this:
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo
- https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by joshuanazareth97** [comment]
@saihaj @maoueh Have done as requested above and created the PR, do let me know if anything is missed
