### ISSUE TITLE
fix `etherlink-testnet` url

### ISSUE THREAD

**Issue by yash251** [graphprotocol/graph-tooling#1622]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

fix `etherlink-testnet` url for fetching ABI and startBlock for verified contracts

### Reproduction

-

### Steps to Reproduce the Bug or Issue

init a subgraph and select etherlink-testnet.
enter verified contract address

### Expected behavior

expected to fetch but shows
```
✔ Ethereum network · etherlink-testnet
✔ Contract address · 0xe312BCe55eb1b932631C28a78296b96A49F600c5
✖ Failed to fetch ABI from Etherscan: getaddrinfo ENOTFOUND api-etherlink-testnet.etherscan.io
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `@graphprotocol/*` version(s): [e.g. 2.6.2]

**Comment by saihaj** [comment]
[@graphprotocol/graph-cli@0.69.2](https://github.com/graphprotocol/graph-tooling/releases/tag/%40graphprotocol%2Fgraph-cli%400.69.2)
