### ISSUE TITLE
etherscan requests failing

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1702]
Looks like etherscan made a change where it requires API keys so now all the requests for `graph init` are failing

**Comment by saihaj** [comment]
one way is we do what is being suggested https://github.com/graphprotocol/graph-tooling/issues/1001

**Comment by saihaj** [comment]
we can also create a Ethercan compat Cloudflare worker. So the API is similar to how Etherscan works but under the hood we can fetch from various datasources. Since the ABIs for a contract address are immutable we can just cache them forever and just serve the content from CDN in almost all the cases

**Comment by craigtutterow** [comment]
We could use the BlockScout smart contract API. Blockscout is in a contract verification alliance with Sourcify that was mentioned in #1001. API docs are here: https://eth.blockscout.com/api-docs. Relevant one is the `/smart-contract/{address-hash}` endpoint

**Comment by fschoell** [comment]
added a workaround for this in #1736 which proxies requests for now until we have a better and ideally decentralised solution
