### ISSUE TITLE
Rely on chain registry for list of supported networks

### ISSUE THREAD

**Issue by alex-pakalniskis** [graphprotocol/graph-tooling#1744]
### Which packages are impacted by your issue?

@graphprotocol/graph-cli

### Describe the issue

Subgraph Studio's list of supported networks is currently the "source of truth" for CLI. 

### Requirements
CLI should have a cache of the supported networks so it doesn't need to contact the internet to get started

**Comment by YaroShkvorets** [comment]
Implemented in v0.93.0
