### ISSUE TITLE
Subgraph source is not clear during `graph init`

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-tooling#1855]
When I initialize a subgraph, after selecting the chain I have to select the source:
```
$ graph init
 ›   Warning: In next major version, this flag will be removed. By default we will
 ›   stop initializing a Git repository.
✔ Network · Base Mainnet · base · https://base.blockscout.com
? Source …
❯ Smart contract
  Substreams
```

Without internal information about the difference of subgraphs and Substreams-powered subgraphs, this is not obvious. I suggest to rename "Smart contract" to "Graph Node (default)". Reasoning: It looks like here we can select the "extract" part from ETLQ. And we can delegate this to Graph Node or to Substreams. I'm not 100% sure this is the best naming but probably better than what we have now.

**Comment by YaroShkvorets** [comment]
I feel like "Smart Contract" makes sense here because when you select "Substreams" you are prompted for substreams package url/path on the next step. And when you select "Smart Contract" you are prompted for smart contract address on the next step. Seems fitting.

"Graph Node" on the other hand, feels ambiguous because Substreams-powered subgraphs are also deployed on Graph Node. 

Open for discussion.

**Comment by schmidsi** [comment]
I see. What about "Smart Contract (default)" then? To clearly indicate, that this is the default path and if I don't know what to choose, I can safely move forward with that one?

**Comment by YaroShkvorets** [comment]
What about "Smart Contract (native)"?

I like the idea to calling them "native subgraphs" as opposed to "substreams-powered subgraphs" or "dataset-powered subgraphs" and whatever other subgraph sources we come up with in the future.

But that's probably more of a higher-level discussion.

Either way works for me.

**Comment by matthewdarwin** [comment]
The "if you are confused pick this one" mentality is important as @schmidsi mentions.

**Comment by schmidsi** [comment]
I like your reasoning about "native", that being said, a new user might not get it. So "(default)" seem to be more clear to me.

**Comment by schmidsi** [comment]
But I'm open to other suggestions. One possibility would be to not even ask for "substreams" during the "init" dialog and hide it behind a flag. Why? Because I assume 90+ percent of the time, people want to initialize a native subgraph.

**Comment by YaroShkvorets** [comment]
Sounds good, "(default)" it is
