### ISSUE TITLE
Error during auth because I don't have X11 server

### ISSUE THREAD

**Issue by come-maiz** [graphprotocol/graph-tooling#259]
I'm trying to run the graph in a digital ocean droplet, so it doesn't have any GUI.
When I run `auth`, I get an error:
```
$  graph auth https://api.thegraph.com/deploy/ <token>
Error: Error storing access token with libsecret (usually gnome-keyring or ksecretservice): Error: Cannot autolaunch D-Bus without X11 $DISPLAY
    at saveAccessToken (/home/ubuntu/node/lib/node_modules/@graphprotocol/graph-cli/src/command-helpers/auth.js:70:13)
```

**Comment by Jannis** [comment]
Graph CLI uses [node-keytar](https://github.com/atom/node-keytar) for storing access tokens natively. On Linux this requires D-Bus and a libsecret service, which it is trying to auto-launch in your case.

You may be able to run `graph auth` inside `dbus-launch` to avoid the auto-launch/X11 problem. We do this for CI as well: https://github.com/graphprotocol/graph-cli/blob/master/.travis.yml

**Comment by Jannis** [comment]
Let us know if it works for you. If it does, we'll add it to our docs.

**Comment by elopio** [comment]
`python-gnomekeyring` is no longer in Ubuntu 18.04, so I'm not sure how to run that step.

**Comment by Npizza** [comment]
I am facing the same problem!

**Comment by Solexplorer** [comment]
Me too! 

I get the error: ```
Could not get access token from libsecret (usually gnome-keyring or ksecretservice): Cannot autolaunch D-Bus without X11 $DISPLAY
Continuing without an access token

✖ HTTP error creating the subgraph: ECONNRESET
```

**Comment by leoyvens** [comment]
This issue can be circumvented by passing the access token through the CLI with `--access-token <token>`.

**Comment by Solexplorer** [comment]
Where do I get the access token @leoyvens ?

**Comment by Solexplorer** [comment]
Running `graph auth https://api.thegraph.com/deploy/ <ACCESS_TOKEN>
` gives the same issue

`Error: Error storing access token with libsecret (usually gnome-keyring or ksecretservice): Error: Cannot autolaunch D-Bus without X11 $DISPLAY
    at saveAccessToken (/home/fred/.nvm/versions/node/v10.15.1/lib/node_modules/@graphprotocol/graph-cli/src/command-helpers/auth.js:70:13)`

**Comment by luckyyang** [comment]
Fixed with:
```bash
graph deploy --access-token YOUR_TOKEN \
    --debug \
    --node https://api.thegraph.com/deploy/ \
    --ipfs https://api.thegraph.com/ipfs/ \
    <GITHUB_USERNAME>/<SUBGRAPH_NAME>
```

**Comment by wafflemakr** [comment]
> Fixed with:
> 
> ```shell
> graph deploy --access-token YOUR_TOKEN \
>     --debug \
>     --node https://api.thegraph.com/deploy/ \
>     --ipfs https://api.thegraph.com/ipfs/ \
>     <GITHUB_USERNAME>/<SUBGRAPH_NAME>
> ```

This works perfectly, thanks!

**Comment by azf20** [comment]
closing as similar to https://github.com/graphprotocol/graph-tooling/issues/569
