### ISSUE TITLE
Add .gitignore and split up the subgraph name cli entry command

### ISSUE THREAD

**Issue by davekaj** [graphprotocol/graph-tooling#391]
I noticed at Eth waterloo that no .gitignore gets created. We should ignore the `./generated` folder, and node modules. 

Also, one of our users kept trying to enter just a subgraph name, and would then be told to do `/username/subgraphname` . Would it make more sense to split this into two commands?

**Comment by Jannis** [comment]
I'm not sure I understand that second part. Creating a `.gitignore` makes a ton of sense though.

**Comment by davekaj** [comment]
Second part would be instead of the cli prompt
```
please enter your subgraph name:
```
and the user is supposed to know it is `<YOUR_GITHUB_HANDLE> / subgraph name`

It would be 
```
please enter your github handle
```
And then :
``` 
please enter your subgraph name
```
And then we compose it for them and let them know that their subgraph name is a combination of the two

I think this is a slightly better UX

**Comment by Jannis** [comment]
Ah, that's fair enough, we can think about how to do this best.

**Comment by Jannis** [comment]
Maybe what we should do is
```
Subgraph name (e.g. `githubuser/mydao`):
```
Because `Please enter your subgraph name` might suggest to people that they should type in e.g. `My DAO` or something, not the URL handle for the subgraph.

**Comment by davekaj** [comment]
Yeah I like that idea
