### ISSUE TITLE
Mutations: Validate Exported Types

### ISSUE THREAD

**Issue by dOrgJelli** [graphprotocol/graph-tooling#440]
Currently the [mutations integration](https://github.com/graphprotocol/graph-cli/pull/406) only checks for the presence of a types.d.ts file, but does not validate the contents.

Ideally we'd want to validate the following types:
- Config
- State
- EventMap
- Any custom event payload

I think that the best route for implementing this would be to use the Typescript run-time directly. Possibly something like this: https://github.com/microsoft/TypeScript/wiki/Using-the-Compiler-API#using-the-type-checker

**Comment by azf20** [comment]
Closing as stale
