### ISSUE TITLE
Allow custom scalar types

### ISSUE THREAD

**Issue by fubhy** [graphprotocol/graph-tooling#499]
It's currently not possible to define custom scalar types in the graphql schema.

Adding full support with custom SerDe would be great, but a simple solution could be to just allow the definition of new scalar types that extend existing built-in scalars through e.g. directives:

```gql
scalar Date @extends("BigInt")
```

This would allow us to implement upcasting / automatic type conversion on the client side e.g. in apollo or urql while processing the query response.

It would vastly improve the developer experience for dealing with dates, bigint / bigdecimal (automatically wrap them in bn.js / bignumber.js on the client) and others.

I only briefly dug through the relevant code but it seems like this would be fairly simple to implement as a plain mapping. `graph-ts` and the graph-node would simply continue to treat the Date from my example as a BigInt but the introspection query would return it as a `Date` scalar, giving me the option to generate code for automatic type conversion on the client.

**Comment by alex-pakalniskis** [comment]
Not exactly custom scalar types, but `Timeseries` scalar type is available in subgraphs i.e. datetime data that can be aggregated.
