### ISSUE TITLE
"graph init --from-example" fails with node v12.5.0

### ISSUE THREAD

**Issue by mauerv** [graphprotocol/graph-tooling#514]
I was following the Quick Start guide and running the "graph init --from-example" command kept failing with:

`✖ Failed to install dependencies: Command failed: yarn
error /Users/mauerv/Crypto/the-graph-experiments/the-graph-experiment/node_modules/sha3: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/mauerv/Crypto/the-graph-experiments/the-graph-experiment/node_modules/sha3`

Downgrading to node v10.16.0 fixed the issue.

Edit: If you want to see the entire log: https://pastebin.com/pUZq1SCS

**Comment by ezpod** [comment]
same issue.

**Comment by tekknikk** [comment]
+1

**Comment by azf20** [comment]
Closing as I think this is stale, please re-open if not
