### ISSUE TITLE
Don't generate accessors for `@derivedFrom` fields

### ISSUE THREAD

**Issue by nlordell** [graphprotocol/graph-tooling#561]
Currently, entities defined as
```graphql
type Foo @entity {
  # ...
  bars: [Bar!]! @derivedFrom(field: "foo")
}
```

Generate AssemblyScript accessors like:
```ts
export class Foo extends Entity {
  // ...
  get bars(): Array<string> {
    let value = this.get("bars");
    return value.toStringArray();
  }
  set bars(value: Array<string>) {
    this.set("bars", Value.fromStringArray(value));
  }
}
``` 

It is my understanding that these values are currently not available to mappings, so the `get` should not be generated.

Additionally, I also suspect that the `set` should also not be generated, but this is being tracked in a separate related issue #381

**Comment by azf20** [comment]
The underlying functionality is being changed to support fetching fields https://github.com/graphprotocol/graph-node/issues/4004
