### ISSUE TITLE
GitHub reporting high severity vulnerablity in graph-cli dependency

### ISSUE THREAD

**Issue by wbnns** [graphprotocol/graph-tooling#598]
Report: https://github.com/advisories/GHSA-4w2v-q235-vp99

Context:
![image](https://user-images.githubusercontent.com/1130872/103624683-2907b300-4f3a-11eb-819b-cb42170a6020.png)

**Comment by saihaj** [comment]
we have updated dependencies and have automated flow so should no longer be an issue. Feel free to report again if you find something we may have missed
