### ISSUE TITLE
Make integration tests retry failed `docker pull` attempts 

### ISSUE THREAD

**Issue by tilacog** [graphprotocol/graph-tooling#656]
GitHub actions workflows are breaking constantly due to failure to pull docker images for our integration tests.

We should implement a strategy to retry failed pull attempts whenever those errors occur.

_Originally posted by @leoyvens in https://github.com/graphprotocol/graph-node/pull/2444#issuecomment-834700119_

**Comment by saihaj** [comment]
I think now the CI here is less flakey compared to before. But we still have some memory leaks in the Jest tests for Cli which need to be addressed separately
