### ISSUE TITLE
Failed to deploy graph node - "Invalid operation type error. at line 59 column 3"

### ISSUE THREAD

**Issue by peripheralist** [graphprotocol/graph-tooling#703]
I was able to deploy this subgraph initially, but now I'm unable to deploy new versions. I can run `graph codegen` and `graph build` without any issues.

Here's the output of running `graph deploy --studio juicebox`

The error at the end isn't giving me enough information to debug.

I'm using graph-cli version 0.21.0, node v16.5.0, running on a Mac M1

```
✔ Version Label (e.g. v0.0.1) · 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.1 to 0.0.2
  Skip migration: Bump mapping apiVersion from 0.0.2 to 0.0.3
  Skip migration: Bump mapping apiVersion from 0.0.3 to 0.0.4
  Skip migration: Bump mapping specVersion from 0.0.1 to 0.0.2
✔ Apply migrations
✔ Load subgraph from subgraph.yaml
  Compile data source: Projects => build/Projects/Projects.wasm
  Compile data source: TerminalV1 => build/Projects/Projects.wasm (already compiled)
✔ Compile subgraph
  Copy schema file build/schema.graphql
  Write subgraph file build/Projects/abis/Projects.json
  Write subgraph file build/TerminalV1/abis/TerminalV1.json
  Write subgraph manifest build/subgraph.yaml
✔ Write compiled subgraph to build/
  Add file to IPFS build/schema.graphql
                .. Qmd9z2gQh9negCbgJvjcQHEnv12cLUs5PNawWkiLeUxyu4
  Add file to IPFS build/Projects/abis/Projects.json
                .. QmcQ6Jazax2Zs7nS5yiatJfBruLbnDgPh1Z6s8Ymo2R9Bn
  Add file to IPFS build/TerminalV1/abis/TerminalV1.json
                .. Qma83sCmBYhEETWk1FnicgxpVuXFV9ffY6PKzHcVTdDtMX
  Add file to IPFS build/Projects/Projects.wasm
                .. QmbEFthRpcD9A9ZcySbZe9Q2BBZhDSEtzZVUdFbH4QFBhr
  Add file to IPFS build/Projects/Projects.wasm
                .. QmbEFthRpcD9A9ZcySbZe9Q2BBZhDSEtzZVUdFbH4QFBhr (already uploaded)
✔ Upload subgraph to IPFS

Build completed: QmVKSTRM8E693ZVXtBVMmbN32nmTKKx8SkDdwfe1cwSkNV

✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: subgraph resolve error: resolve error: Serialization error: Invalid operation type error. at line 59 column 3

```

**Comment by azf20** [comment]
Are you using solidity 8? I think you have maybe encountered this error https://github.com/graphprotocol/graph-node/issues/2577

**Comment by dmihal** [comment]
I just hit this error, it seems to come from Solidity 0.8.4 errors.

These errors appear in the ABI file like this:

```
  { "inputs": [], "name": "MustBeOwner", "type": "error" },
```

It seems that the graph-cli needs to add support for parsing these errors.

**Comment by peripheralist** [comment]
@azf20 I am using solidity 8.6, looks like that's exactly what I've been blocked on

@dmihal have you found a workaround yet, like trying to strip customErrors from the abi before using it to compile a subgraph? theoretically that would still be usable no?

**Comment by peripheralist** [comment]
Update: I tried deploying this subgraph with the errors removed from the ABI and it failed syncing. I'm guessing this is because of the ABI mismatch https://thegraph.com/studio/subgraph/juicebox/

**Comment by azf20** [comment]
@dmihal yes - the parsing is actually required on the graph-node side (it is there that the ABI is being parsed, and rejected)

@peripheralist yes that is the correct fix - I don't think there is a reason syncing would fail because of the ABI mismatch, so I expect that something else went wrong. If you can share the deployment hash we could take a look.

**Comment by peripheralist** [comment]
Thanks, is this the deployment hash? `QmQoZzZCjuAym1Wy31hehErn5HfHwDKAXbEGuRLkv3X78g`

![image](https://user-images.githubusercontent.com/79433522/126401251-95e0adbc-397e-480a-9a6a-92139b9419e2.png)

**Comment by azf20** [comment]
Yes it looks like that has failed for another reason:
```
failed to process trigger: block #12834007 (0x5c38…57b1), transaction c815a8587a49d7379322be6ce69f6c5d7c1995cb3754d01a96ecd549793d6d36: Entity PayEvent[0xc815a8587a49d7379322be6ce69f6c5d7c1995cb3754d01a96ecd549793d6d36-115]: missing value for non-nullable field `memo`\twasm backtrace:\t    0: 0x13ea - <unknown>!generated/schema/PayEvent#save\t    1: 0x1447 - <unknown>!src/mapping/handlePay\t
```

**Comment by peripheralist** [comment]
thanks @azf20 , seems like that's saying an empty value was passed for `memo`. in that case an error would be thrown, except that i removed the errors from the abi... which is probably causing this to fail? do you have any ideas for a workaround?

also, is there somewhere i could find those logs so i don't have to bug you for them?

**Comment by azf20** [comment]
@peripheralist the removed errors in the ABI are not related to this subgraph failure (they are thrown on an error in the EVM execution, not the subgraph execution).

it looks like you have a non-nullable field in your schema, and you are trying to save a null value. You can query for these kinds of errors per [here](https://thegraph.com/docs/developer/deploy-subgraph-hosted#checking-subgraph-health)

**Comment by peripheralist** [comment]
@azf20 yes! didn't understand the non-null GraphQL type before, but i'm clear on it now. syncing succeeded. thanks for the help!

for anyone else coming here using solidity 8, just confirming that you can still deploy your subgraph by manually removing the errors from your ABI 👍

**Comment by peripheralist** [comment]
> You can query for these kinds of errors per [here](https://thegraph.com/docs/developer/deploy-subgraph-hosted#checking-subgraph-health)

@azf20 i'm trying to follow the instructions in that link, but it seems like this is for the legacy explorer—i'm using studio. what should i be using for `subgraphName`, and where is the deployment hash relevant?

![image](https://user-images.githubusercontent.com/79433522/126430909-086ca718-ffb1-4f3c-8eea-76c9e825d4f3.png)

**Comment by azf20** [comment]
hi @peripheralist apologies yes those docs apply to the legacy explorer, you should be able to run
```query MyQuery {
  indexingStatuses(subgraphs: ["QmQoZzZCjuAym1Wy31hehErn5HfHwDKAXbEGuRLkv3X78g"]) {
    synced
    health
    fatalError {
      message
      block { number }
      handler
    }
    subgraph
    chains {
      chainHeadBlock {
        number
      }
      latestBlock {
        number
      }
    }
  }
}```
on the same endpoint.
Conscious that this discussion has moved off the topic of this issue, please [join our Discord](https://discord.gg/vtvv7FP) and use #subgraph-development for ongoing discussion

**Comment by azf20** [comment]
Errors are now supported, closing this, thanks!
