### ISSUE TITLE
issue to install @graphprotocol/graph-cli in windows 10

### ISSUE THREAD

**Issue by bignosecripto** [graphprotocol/graph-tooling#717]
I had a problem that I believe many people had when trying to install @graphprotocol / graph-cli where the following error occurs

**PS C:\Users\user> npm install -g @graphprotocol/graph-cli
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/AssemblyScript/assemblyscript.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2021-08-07T18_04_36_221Z-debug.log**

The problem was due to the fact that node could not find the global "git" to install the @graphprotocol/graph-cli dependency, even though I had installed git through the command "npm install git".

But man how did you solve this?

I needed to declare the global "git" in the windows environment variables.

Step by step:

- -look for the cmd/git.exe directory inside your GitHub Desktop file location (on my computer the directory is: C:\Users\<youruser>\AppData\Local\GitHubDesktop\app-2.9.0\resources\app \git\cmd\git.exe)
- -find your directory go to your computer's properties;
- -advanced system settings
- - environment variables
- -system variables
- -select Path and click "edit"
- -click "new"
- -and enter the directory: "C:\Users\youruser\AppData\Local\GitHubDesktop\app-2.9.0\resources\app\git\cmd\"

ps: out Bolsonaro

#565

**Comment by nawab69** [comment]
I have also the same problem on Mac OS

**Comment by Pelumi527** [comment]
For Windows 10, using npm to install instead of yarn solved the issue for me

**Comment by Div-Denis** [comment]
connot ,npm or yarn,i cannot install this

**Comment by saihaj** [comment]
I think we did fix this but if you are still having issues please create a new issue
