### ISSUE TITLE
ERRRO: When select Mumbai( Matic testnet ):   Failed to fetch ABI from Etherscan: request to

### ISSUE THREAD

**Issue by sagarjethi** [graphprotocol/graph-tooling#730]
Failed to fetch ABI from Etherscan: request to https://api-mumbai.etherscan.io/api?module=contract&action=getabi&address=address failed, reason: getaddrinfo 

ENOTFOUND api-mumbai.etherscan.io
✖ ABI file (path)

**Comment by sagarjethi** [comment]
Yes @schmidsi  We can change that to https://mumbai.polygonscan.com/apis#contracts

Here is following API we can use : https://api-testnet.polygonscan.com/api?module=contract&action=getabi&address=0x2791bca1f2de4661ed88a30c99a7a9449aa84174&apikey=YourApiKeyToken

Please check that

**Comment by sagarjethi** [comment]
Also, cli asking "ABI file (path )"   what link should provide there and what formate  path link would be there

**Comment by akorede12** [comment]
Hello, I have this issue now when trying to create a subgraph for my project, my contract is deployed to the mumbai testnet. After using graph init it fails to get the contracts abi  "✖ Failed to fetch ABI from Etherscan: ABI not found, try loading it from a local file" and when I try to reference abi from my local file it just says "file does not exist". Please help

**Comment by azf20** [comment]
This is now supported https://github.com/graphprotocol/graph-tooling/blob/main/packages/cli/src/command-helpers/abi.ts#L164
