### ISSUE TITLE
Allow user to generate the boilerplate with multiple ABIs and contracts

### ISSUE THREAD

**Issue by vipineth** [graphprotocol/graph-tooling#757]
Using `graph init` we can generate the boilerplate. While generating the boilerplate we can also pass parameters like abi and contract address.

If we can add a way for user to pass multiple ABIs and contracts that would be really helpful.

You can also refer to this tweet (https://twitter.com/vipineth/status/1445947456944934913)

**Comment by azf20** [comment]
this is now supported via `graph add`
