### ISSUE TITLE
How to auto create an existing contract?

### ISSUE THREAD

**Issue by cucaixanh** [graphprotocol/graph-tooling#797]
I had started on ec2 server.
Every time I have a new contract. i will ssh into it and execute.
I want this automatically? 
Thanks you.

```
graph init \
  --product subgraph-studio
  --from-contract <CONTRACT_ADDRESS> \
  [--network <ETHEREUM_NETWORK>] \
  [--abi <FILE>] \
  <SUBGRAPH_SLUG> [<DIRECTORY>]

**Comment by azf20** [comment]
Hi @tomhardyctl - I am not sure I understand the exact request, what is it you want to automate? The running of the `graph init` command?

**Comment by saihaj** [comment]
not so sure what we are trying to automate here. The CLI is able to take ABI and generate now how it is consumed is on end user. Feel free to re-open with more details.
