### ISSUE TITLE
`graph init --abi path/to/Contract.abi` does not work

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-tooling#818]
It seems like the CLI arguments are ignored and the wizard just starts as if there weren't any.

**Comment by azf20** [comment]
thanks @schmidsi - I think I was able to replicate, I am not sure why the `initial` value isn't working here: https://github.com/graphprotocol/graph-cli/blob/9ec15d2f81c75c27a960375c23f8c2e793b6045b/src/commands/init.js#L215 cc @otaviopace

**Comment by schmidsi** [comment]
Uh, if I remember correctly, there were some other arguments given. But I have to reproduce again.

**Comment by saihaj** [comment]
I think this would have been fixed with we moved to #1055  but if you are still facing please create a new issue and follow the bug report template.
