### ISSUE TITLE
HTTP error deploying the subgraph 504

### ISSUE THREAD

**Issue by montanaflynn** [graphprotocol/graph-tooling#843]
Quite often I receive this error when deploying:
```
Build completed: Qmbe8aBqXW5ypmKEP3KmS9WWU578oA1bMm875NXwaZMpYv
✖ HTTP error deploying the subgraph 504
````

Then when retrying with the same version I get the following error:

```
Build completed: Qmbe8aBqXW5ypmKEP3KmS9WWU578oA1bMm875NXwaZMpYv
✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Version label already exists.
```

**Comment by azf20** [comment]
Hi @montanaflynn - thanks, is the version available to view in the studio?

**Comment by montanaflynn** [comment]
This was an intermittent error, retrying with a new version always fixed the issue. The subgraph isn't ready to share with the world just yet.

**Comment by montanaflynn** [comment]
Also got this error today:

```
✔ Upload subgraph to IPFS

Build completed: QmXTokWkL1dp9yersSPneg9274wdTW2UEETUXrpFZ3iBue

✖ HTTP error deploying the subgraph ECONNRESET
```

Retrying also resulted in:

```
✖ Failed to deploy to Graph node https://api.studio.thegraph.com/deploy/: Version label already exists.
```

**Comment by azf20** [comment]
Closing, please re-open if you are still having issues with deployment

**Comment by amandafanny** [comment]
I have same problem

**Comment by agustinjch** [comment]
Same error here. Any tips on how to debug this?

Thanks

**Comment by AnPiakhota** [comment]
Why has it been closed? It happens from time to time and it is the Graph CLI that closes the connection if the graphnode does not deploy it within 5 seconds. It looks like there is nothing to tweak connection timeout on the server side. 

![image](https://github.com/graphprotocol/graph-tooling/assets/37925745/1351f77d-99a7-45dd-b608-3565da93a614)

**Comment by qiaopengjun5162** [comment]
<img width="780" alt="image-20240720105810386" src="https://github.com/user-attachments/assets/213707b6-8a89-4666-a2b2-19ed3473631d">
Help, someone help me, I've been stuck here for 2 days

**Comment by qiaopengjun5162** [comment]
graph --version
@graphprotocol/graph-cli/0.78.0 darwin-arm64 node-v22.1.0
