### ISSUE TITLE
issue to install @graphprotocol/graph-cli on Ubuntu

### ISSUE THREAD

**Issue by sheriff-rango** [graphprotocol/graph-tooling#850]
I want to install `@graphprotocol/graph-cli` on Ubuntu. I have tried to install `graph-cli` with `npm` and `yarn`, both of them.

    # NPM
    npm install -g @graphprotocol/graph-cli

    # Yarn
    yarn global add @graphprotocol/graph-cli

But after that when I tried `graph init`, I met this error `bash: /usr/bin/graph: No such file or directory`.

What can I do? What was my fault?

Is anybody help me with this issue?

**Comment by alex-pakalniskis** [comment]
unable to reproduce on ubuntu
