### ISSUE TITLE
Error during codegen

### ISSUE THREAD

**Issue by amrap030** [graphprotocol/graph-tooling#859]
Hello together,

i am receiving the following error on `codegen`:

<img width="1579" alt="Bildschirmfoto 2022-03-23 um 13 32 33" src="https://user-images.githubusercontent.com/35061229/159700106-2f0f67de-aab0-4715-9c61-483e21cb9632.png">

The code is available in https://github.com/amrap030/subgraph

Node version: v14.17.0
Npm version: 6.14.13

I would be glad if you can have a look at it. Thank you in advance!

**Comment by azf20** [comment]
hi @amwalke closing this, please ping if this issue is still live
