### ISSUE TITLE
Is there a way I can create multiple subgraphs quickly?

### ISSUE THREAD

**Issue by cucaixanh** [graphprotocol/graph-tooling#861]
For example I have 30 Contracts same Network Ethereum. Is there a way I can create multiple subgraphs quickly?

**Comment by schmidsi** [comment]
This is being worked on: https://github.com/graphprotocol/graph-cli/issues/838

Although your use-case seems to me more like candidate for [Data Source Templates](https://thegraph.com/docs/en/developer/create-subgraph-hosted/#data-source-templates). Did you deploy all those contracts by yourself from or did you generate them through a factory contract?

**Comment by schmidsi** [comment]
With the recently introduced `graph add` and enhanced `graph init` it is now possible to create a subgraph quickly that indexes a lot of contracts on the same network. If you need to index on different networks, one subgraph per network is needed. I'm closing this issue now, feel free to reopen if your concern is not addressed.
