### ISSUE TITLE
Error when deploying to nonexistent subgraph name in hosted not helpful

### ISSUE THREAD

**Issue by lutter** [graphprotocol/graph-tooling#868]
Trying to deploy to a name that doesn't exist in the hosted service just results in a `HTTP error deploying the subgraph 504` in `graph-cli`. The error should tell the user what went wrong (subgraph doesn't exist) and how to fix it (go to the explorer and create the subgraph)

**Comment by saihaj** [comment]
https://github.com/graphprotocol/graph-tooling/issues/1082 will actually help with this

**Comment by qiaopengjun5162** [comment]
@lutter Have you solved your deployment problem? How did you solve it?

**Comment by saihaj** [comment]
hosted service is shut down and we no longer allow creating new subgraphs
