### ISSUE TITLE
WSL/Ubuntu/Linux  fix for `static BYTES = Symbol("Bytes")  SyntaxError: Unexpected token =` - not a bug report

### ISSUE THREAD

**Issue by dimitrovmaksim** [graphprotocol/graph-tooling#881]
**This is not a bug report** 

I'm opening this issue in case someone is searching for this error. The reason for this error is using an unsupported node version, usually node v10.x, that is being installed with `apt install nodejs` on Ubuntu. Currently supported versions are [12, 14, 16](https://github.com/graphprotocol/graph-cli/commit/3f366f1260f59296ec3c09e7c694ba8b55ba0354)

Instructions on how to install a newer node version can be found [here](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)
Alternatively you can use [nvm](https://github.com/nvm-sh/nvm) to manage your Node versions 

If you are using WSL (Windows Subsystem for Linux) and have issues running matchstick with the `graph test` command, please check out the instructions [here](https://github.com/LimeChain/matchstick#wsl-windows-subsystem-for-linux-) - thanks to @axiomatic-aardvark

**Comment by saihaj** [comment]
we support now 14.x + of Node since it is LTS 
![CleanShot 2023-02-22 at 13 12 47](https://user-images.githubusercontent.com/44710980/220718752-dd4c6b0a-c980-4b6e-b4b6-8ea71cba296c.png)


soon with #1081 we wouldn't even need users to install Node.js
