### ISSUE TITLE
Automatically populate `startBlock` upon `graph-init --from-contract`

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-tooling#917]
A very common pitfall for first time Graph users is that they do not know about the `startBlock` and their subgraph takes way long to sync without results because it is indexing from genesis. We could just download this from Etherscan, no?

**Comment by saihaj** [comment]
we added support in this release https://github.com/graphprotocol/graph-tooling/releases/tag/release-1676308812812
