### ISSUE TITLE
Add Optimism Goerli ⭕

### ISSUE THREAD

**Issue by 3lLobo** [graphprotocol/graph-tooling#964]
For my hackathon project I would like to index a contract deployed to Optimism Goerli.
Could you update the list which appears on `init` to choose from on which network the smrtCntrct is deployed?

Afaik Optimism Kovan got replaced by Optimism Goerli as official testnet.
The [website](https://thegraph.com/docs/en/deploying/deploying-a-subgraph-to-hosted/) already updated this.

Lmk if I can just use Kovan as Goerli or if I need to wait for the next version 🤗

![image](https://user-images.githubusercontent.com/25290565/190929005-b472bcda-c18f-4488-9bce-268d1d450c32.png)

**Comment by azf20** [comment]
Hi! Yes, we need to update the list on `init`, thanks for the note - before we do, you can pick another network and edit the network name directly on the `subgraph.yaml`

**Comment by saihaj** [comment]
we added support for these in CLI. Try `0.41.1`
